import type {ViewDefinition, ViewKey, SelectOption} from './types';

const BOOL_OPTIONS: SelectOption[] = [
    {label: 'Any', value: ''},
    {label: 'True', value: 'true'},
    {label: 'False', value: 'false'},
];

const PARTY_ID_TYPE_OPTIONS: SelectOption[] = [
    {label: 'Any', value: ''},
    {label: 'MSISDN', value: 'MSISDN'},
    {label: 'EMAIL', value: 'EMAIL'},
    {label: 'PERSONAL_ID', value: 'PERSONAL_ID'},
    {label: 'BUSINESS', value: 'BUSINESS'},
    {label: 'DEVICE', value: 'DEVICE'},
    {label: 'ACCOUNT_ID', value: 'ACCOUNT_ID'},
    {label: 'IBAN', value: 'IBAN'},
    {label: 'ALIAS', value: 'ALIAS'},
];

export const VIEW_DEFINITIONS: ViewDefinition[] = [
    {
        key: 'participant-onboarding',
        group: 'Participant',
        title: 'Participant Onboarding',
        menuLabel: 'Onboarding',
        subtitle: 'Start and review participant onboarding activities from the portal.',
        endpoint: '',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'id',
    },
    {
        key: 'participant-add-new-currency',
        group: 'Participant',
        title: 'Participant Add New Currency',
        menuLabel: 'Add New Currency',
        subtitle: 'Open the participant currency expansion workflow and related handoff details.',
        endpoint: '',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'id',
    },
    {
        key: 'inbound-parties',
        group: 'Inbound',
        title: 'Inbound Parties',
        menuLabel: 'Parties',
        subtitle: 'Track inbound party resolution callbacks and errors.',
        endpoint: '/audit/inbound/parties',
        criteriaFields: [
            {key: 'payerFsp', label: 'Payer FSP', type: 'text', placeholder: 'wallet-a'},
            {key: 'payeeFsp', label: 'Payee FSP', type: 'text', placeholder: 'switch'},
            {key: 'partyIdType', label: 'Party ID Type', type: 'select', options: PARTY_ID_TYPE_OPTIONS},
            {key: 'partyId', label: 'Party ID', type: 'text', placeholder: '959420000111'},
            {key: 'subId', label: 'Sub ID', type: 'text', placeholder: 'optional (use "null" to query null)'},
            {key: 'error', label: 'Has Error', type: 'select', options: BOOL_OPTIONS},
            {key: 'createdAtStart', label: 'Created At (Start)', type: 'datetime'},
            {key: 'createdAtEnd', label: 'Created At (End)', type: 'datetime'},
            {key: 'completedAtStart', label: 'Completed At (Start)', type: 'datetime'},
            {key: 'completedAtEnd', label: 'Completed At (End)', type: 'datetime'},
        ],
        orderColumns: [
            {label: 'Created At', value: 'createdAt'},
            {label: 'Completed At', value: 'completedAt'},
            {label: 'ID', value: 'id'},
            {label: 'Party ID', value: 'partyId'},
            {label: 'Payer FSP', value: 'payerFsp'},
            {label: 'Payee FSP', value: 'payeeFsp'},
            {label: 'Error', value: 'failed'},
        ],
        columns: [
            {key: 'payerFsp', label: 'Payer'},
            {key: 'payeeFsp', label: 'Payee'},
            {key: 'partyIdType', label: 'Party Type'},
            {key: 'partyId', label: 'Party ID'},
            {key: 'subId', label: 'Sub ID'},
            {key: 'failed', label: 'Failed'},
            {key: 'createdAt', label: 'Created At'},
            {key: 'completedAt', label: 'Completed At'},
        ],
        primaryKey: 'partyId',
    },
    {
        key: 'inbound-quotes',
        group: 'Inbound',
        title: 'Inbound Quotes',
        menuLabel: 'Quotes',
        subtitle: 'Monitor inbound quote callbacks, payloads, and failures.',
        endpoint: '/audit/inbound/quotes',
        criteriaFields: [
            {key: 'payerFsp', label: 'Payer FSP', type: 'text', placeholder: 'wallet-a'},
            {key: 'payeeFsp', label: 'Payee FSP', type: 'text', placeholder: 'switch'},
            {key: 'quoteId', label: 'Quote ID', type: 'text', placeholder: 'uuid'},
            {key: 'error', label: 'Has Error', type: 'select', options: BOOL_OPTIONS},
            {key: 'createdAtStart', label: 'Created At (Start)', type: 'datetime'},
            {key: 'createdAtEnd', label: 'Created At (End)', type: 'datetime'},
            {key: 'completedAtStart', label: 'Completed At (Start)', type: 'datetime'},
            {key: 'completedAtEnd', label: 'Completed At (End)', type: 'datetime'},
        ],
        orderColumns: [
            {label: 'Created At', value: 'createdAt'},
            {label: 'Completed At', value: 'completedAt'},
            {label: 'ID', value: 'id'},
            {label: 'Quote ID', value: 'quoteId'},
            {label: 'Payer FSP', value: 'payerFsp'},
            {label: 'Payee FSP', value: 'payeeFsp'},
            {label: 'Error', value: 'failed'},
        ],
        columns: [
            {key: 'quoteId', label: 'Quote ID'},
            {key: 'payerFsp', label: 'Payer'},
            {key: 'payeeFsp', label: 'Payee'},
            {key: 'failed', label: 'Failed'},
            {key: 'createdAt', label: 'Created At'},
            {key: 'completedAt', label: 'Completed At'},
        ],
        primaryKey: 'quoteId',
    },
    {
        key: 'inbound-transfers',
        group: 'Inbound',
        title: 'Inbound Transfers',
        menuLabel: 'Transfers',
        subtitle: 'Search inbound transfer callbacks by transfer ID and status.',
        endpoint: '/audit/inbound/transfers',
        criteriaFields: [
            {key: 'payerFsp', label: 'Payer FSP', type: 'text', placeholder: 'wallet-a'},
            {key: 'payeeFsp', label: 'Payee FSP', type: 'text', placeholder: 'switch'},
            {key: 'transferId', label: 'Transfer ID', type: 'text', placeholder: 'uuid'},
            {key: 'error', label: 'Has Error', type: 'select', options: BOOL_OPTIONS},
            {key: 'createdAtStart', label: 'Created At (Start)', type: 'datetime'},
            {key: 'createdAtEnd', label: 'Created At (End)', type: 'datetime'},
            {key: 'completedAtStart', label: 'Completed At (Start)', type: 'datetime'},
            {key: 'completedAtEnd', label: 'Completed At (End)', type: 'datetime'},
        ],
        orderColumns: [
            {label: 'Created At', value: 'createdAt'},
            {label: 'Completed At', value: 'completedAt'},
            {label: 'ID', value: 'id'},
            {label: 'Transfer ID', value: 'transferId'},
            {label: 'Payer FSP', value: 'payerFsp'},
            {label: 'Payee FSP', value: 'payeeFsp'},
            {label: 'Error', value: 'failed'},
        ],
        columns: [
            {key: 'transferId', label: 'Transfer ID'},
            {key: 'payerFsp', label: 'Payer'},
            {key: 'payeeFsp', label: 'Payee'},
            {key: 'failed', label: 'Failed'},
            {key: 'createdAt', label: 'Created At'},
            {key: 'completedAt', label: 'Completed At'},
        ],
        primaryKey: 'transferId',
    },
    {
        key: 'outbound-parties',
        group: 'Outbound',
        title: 'Outbound Parties',
        menuLabel: 'Parties',
        subtitle: 'Audit party lookups initiated by outbound flows.',
        endpoint: '/audit/outbound/parties',
        criteriaFields: [
            {key: 'payerFsp', label: 'Payer FSP', type: 'text', placeholder: 'wallet-a'},
            {key: 'payeeFsp', label: 'Payee FSP', type: 'text', placeholder: 'switch'},
            {key: 'partyIdType', label: 'Party ID Type', type: 'select', options: PARTY_ID_TYPE_OPTIONS},
            {key: 'partyId', label: 'Party ID', type: 'text', placeholder: '959420000111'},
            {key: 'subId', label: 'Sub ID', type: 'text', placeholder: 'optional (use "null" to query null)'},
            {key: 'error', label: 'Has Error', type: 'select', options: BOOL_OPTIONS},
            {key: 'createdAtStart', label: 'Created At (Start)', type: 'datetime'},
            {key: 'createdAtEnd', label: 'Created At (End)', type: 'datetime'},
            {key: 'completedAtStart', label: 'Completed At (Start)', type: 'datetime'},
            {key: 'completedAtEnd', label: 'Completed At (End)', type: 'datetime'},
        ],
        orderColumns: [
            {label: 'Created At', value: 'createdAt'},
            {label: 'Completed At', value: 'completedAt'},
            {label: 'ID', value: 'id'},
            {label: 'Party ID', value: 'partyId'},
            {label: 'Payer FSP', value: 'payerFsp'},
            {label: 'Payee FSP', value: 'payeeFsp'},
            {label: 'Error', value: 'failed'},
        ],
        columns: [
            {key: 'payerFsp', label: 'Payer'},
            {key: 'payeeFsp', label: 'Payee'},
            {key: 'partyIdType', label: 'Party Type'},
            {key: 'partyId', label: 'Party ID'},
            {key: 'subId', label: 'Sub ID'},
            {key: 'failed', label: 'Failed'},
            {key: 'createdAt', label: 'Created At'},
            {key: 'completedAt', label: 'Completed At'},
        ],
        primaryKey: 'partyId',
    },
    {
        key: 'outbound-quotes',
        group: 'Outbound',
        title: 'Outbound Quotes',
        menuLabel: 'Quotes',
        subtitle: 'Explore outbound quote requests and returned quote callbacks.',
        endpoint: '/audit/outbound/quotes',
        criteriaFields: [
            {key: 'payerFsp', label: 'Payer FSP', type: 'text', placeholder: 'wallet-a'},
            {key: 'payeeFsp', label: 'Payee FSP', type: 'text', placeholder: 'switch'},
            {key: 'quoteId', label: 'Quote ID', type: 'text', placeholder: 'uuid'},
            {key: 'error', label: 'Has Error', type: 'select', options: BOOL_OPTIONS},
            {key: 'createdAtStart', label: 'Created At (Start)', type: 'datetime'},
            {key: 'createdAtEnd', label: 'Created At (End)', type: 'datetime'},
            {key: 'completedAtStart', label: 'Completed At (Start)', type: 'datetime'},
            {key: 'completedAtEnd', label: 'Completed At (End)', type: 'datetime'},
        ],
        orderColumns: [
            {label: 'Created At', value: 'createdAt'},
            {label: 'Completed At', value: 'completedAt'},
            {label: 'ID', value: 'id'},
            {label: 'Quote ID', value: 'quoteId'},
            {label: 'Payer FSP', value: 'payerFsp'},
            {label: 'Payee FSP', value: 'payeeFsp'},
            {label: 'Error', value: 'failed'},
        ],
        columns: [
            {key: 'quoteId', label: 'Quote ID'},
            {key: 'payerFsp', label: 'Payer'},
            {key: 'payeeFsp', label: 'Payee'},
            {key: 'failed', label: 'Failed'},
            {key: 'createdAt', label: 'Created At'},
            {key: 'completedAt', label: 'Completed At'},
        ],
        primaryKey: 'quoteId',
    },
    {
        key: 'outbound-transfers',
        group: 'Outbound',
        title: 'Outbound Transfers',
        menuLabel: 'Transfers',
        subtitle: 'Inspect outbound transfer executions, responses, and failures.',
        endpoint: '/audit/outbound/transfers',
        criteriaFields: [
            {key: 'payerFsp', label: 'Payer FSP', type: 'text', placeholder: 'wallet-a'},
            {key: 'payeeFsp', label: 'Payee FSP', type: 'text', placeholder: 'switch'},
            {key: 'transferId', label: 'Transfer ID', type: 'text', placeholder: 'uuid'},
            {key: 'error', label: 'Has Error', type: 'select', options: BOOL_OPTIONS},
            {key: 'createdAtStart', label: 'Created At (Start)', type: 'datetime'},
            {key: 'createdAtEnd', label: 'Created At (End)', type: 'datetime'},
            {key: 'completedAtStart', label: 'Completed At (Start)', type: 'datetime'},
            {key: 'completedAtEnd', label: 'Completed At (End)', type: 'datetime'},
        ],
        orderColumns: [
            {label: 'Created At', value: 'createdAt'},
            {label: 'Completed At', value: 'completedAt'},
            {label: 'ID', value: 'id'},
            {label: 'Transfer ID', value: 'transferId'},
            {label: 'Payer FSP', value: 'payerFsp'},
            {label: 'Payee FSP', value: 'payeeFsp'},
            {label: 'Error', value: 'failed'},
        ],
        columns: [
            {key: 'transferId', label: 'Transfer ID'},
            {key: 'payerFsp', label: 'Payer'},
            {key: 'payeeFsp', label: 'Payee'},
            {key: 'failed', label: 'Failed'},
            {key: 'createdAt', label: 'Created At'},
            {key: 'completedAt', label: 'Completed At'},
        ],
        primaryKey: 'transferId',
    },
];

export const VIEW_BY_KEY = Object.fromEntries(
    VIEW_DEFINITIONS.map((view: ViewDefinition): [ViewKey, ViewDefinition] => [view.key, view]),
) as Record<ViewKey, ViewDefinition>;
