import type {ViewDefinition, ViewKey, SelectOption} from './types';

const BOOL_OPTIONS: SelectOption[] = [
    {label: 'Any', value: ''},
    {label: 'True', value: 'true'},
    {label: 'False', value: 'false'},
];

const PARTY_ID_TYPE_OPTIONS: SelectOption[] = [
    {label: 'Any', value: ''},
    {label: 'MSISDN', value: 'MSISDN'},
    {label: 'EMAIL', value: 'EMAIL'},
    {label: 'PERSONAL_ID', value: 'PERSONAL_ID'},
    {label: 'BUSINESS', value: 'BUSINESS'},
    {label: 'DEVICE', value: 'DEVICE'},
    {label: 'ACCOUNT_ID', value: 'ACCOUNT_ID'},
    {label: 'IBAN', value: 'IBAN'},
    {label: 'ALIAS', value: 'ALIAS'},
];

export const VIEW_DEFINITIONS: ViewDefinition[] = [
    {
        key: 'hub-add-currency',
        group: 'Hub',
        title: 'Add Currency',
        menuLabel: 'Add Currency',
        subtitle: 'Provision Hub settlement and reconciliation accounts plus the deferred net settlement model for a currency.',
        endpoint: '/hub/currency',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'id',
    },
    {
        key: 'hub-list-participants',
        group: 'Hub',
        title: 'List Participants',
        menuLabel: 'List Participants',
        subtitle: 'Review the participants currently registered in central ledger, including their status and currencies.',
        endpoint: '/participant/list',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'name',
    },
    {
        key: 'hub-add-signing-keys',
        group: 'Hub',
        title: 'Add Signing Keys',
        menuLabel: 'Add Signing Keys',
        subtitle: 'Create or update the JWS signing key pair for Hub.',
        endpoint: '/hub/signing-keys',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'id',
    },
    {
        key: 'participant-onboarding',
        group: 'Participant',
        title: 'Onboard FSP',
        menuLabel: 'Onboard FSP',
        subtitle: 'Provision a new FSP with its endpoint, signing keys, and supported currencies.',
        endpoint: '/participant/onboard',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'id',
    },
    {
        key: 'participant-add-new-currency',
        group: 'Participant',
        title: 'Add Currency',
        menuLabel: 'Add Currency',
        subtitle: 'Enable one or more additional currencies for an existing participant.',
        endpoint: '/participant/currency',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'id',
    },
    {
        key: 'participant-register-endpoint',
        group: 'Participant',
        title: 'Register Endpoint',
        menuLabel: 'Register Endpoint',
        subtitle: 'Register or replace the callback endpoint configuration for an existing participant.',
        endpoint: '/participant/endpoint',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'id',
    },
    {
        key: 'participant-add-signing-keys',
        group: 'Participant',
        title: 'Add Signing Keys',
        menuLabel: 'Add Signing Keys',
        subtitle: 'Create or update the JWS signing key pair for a participant by name.',
        endpoint: '/participant/signing-keys',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'id',
    },
    {
        key: 'inbound-parties',
        group: 'Inbound',
        title: 'Parties',
        menuLabel: 'Parties',
        subtitle: 'Track inbound party resolution callbacks and errors.',
        endpoint: '/audit/inbound/parties',
        criteriaFields: [
            {key: 'payerFsp', label: 'Payer FSP', type: 'text', placeholder: 'wallet-a'},
            {key: 'payeeFsp', label: 'Payee FSP', type: 'text', placeholder: 'switch'},
            {key: 'partyIdType', label: 'Party ID Type', type: 'select', options: PARTY_ID_TYPE_OPTIONS},
            {key: 'partyId', label: 'Party ID', type: 'text', placeholder: '959420000111'},
            {key: 'subId', label: 'Sub ID', type: 'text', placeholder: 'optional (use "null" to query null)'},
            {key: 'error', label: 'Has Error', type: 'select', options: BOOL_OPTIONS},
            {key: 'createdAtStart', label: 'Created At (Start)', type: 'datetime'},
            {key: 'createdAtEnd', label: 'Created At (End)', type: 'datetime'},
            {key: 'completedAtStart', label: 'Completed At (Start)', type: 'datetime'},
            {key: 'completedAtEnd', label: 'Completed At (End)', type: 'datetime'},
        ],
        orderColumns: [
            {label: 'Created At', value: 'createdAt'},
            {label: 'Completed At', value: 'completedAt'},
            {label: 'ID', value: 'id'},
            {label: 'Party ID', value: 'partyId'},
            {label: 'Payer FSP', value: 'payerFsp'},
            {label: 'Payee FSP', value: 'payeeFsp'},
            {label: 'Error', value: 'failed'},
        ],
        columns: [
            {key: 'payerFsp', label: 'Payer'},
            {key: 'payeeFsp', label: 'Payee'},
            {key: 'partyIdType', label: 'Party Type'},
            {key: 'partyId', label: 'Party ID'},
            {key: 'subId', label: 'Sub ID'},
            {key: 'failed', label: 'Failed'},
            {key: 'createdAt', label: 'Created At'},
            {key: 'completedAt', label: 'Completed At'},
        ],
        primaryKey: 'partyId',
    },
    {
        key: 'inbound-quotes',
        group: 'Inbound',
        title: 'Quotes',
        menuLabel: 'Quotes',
        subtitle: 'Monitor inbound quote callbacks, payloads, and failures.',
        endpoint: '/audit/inbound/quotes',
        criteriaFields: [
            {key: 'payerFsp', label: 'Payer FSP', type: 'text', placeholder: 'wallet-a'},
            {key: 'payeeFsp', label: 'Payee FSP', type: 'text', placeholder: 'switch'},
            {key: 'quoteId', label: 'Quote ID', type: 'text', placeholder: 'uuid'},
            {key: 'scenario', label: 'Scenario', type: 'text', placeholder: 'TRANSFER'},
            {key: 'subScenario', label: 'Sub Scenario', type: 'text', placeholder: 'scheme-specific'},
            {key: 'error', label: 'Has Error', type: 'select', options: BOOL_OPTIONS},
            {key: 'createdAtStart', label: 'Created At (Start)', type: 'datetime'},
            {key: 'createdAtEnd', label: 'Created At (End)', type: 'datetime'},
            {key: 'completedAtStart', label: 'Completed At (Start)', type: 'datetime'},
            {key: 'completedAtEnd', label: 'Completed At (End)', type: 'datetime'},
        ],
        orderColumns: [
            {label: 'Created At', value: 'createdAt'},
            {label: 'Completed At', value: 'completedAt'},
            {label: 'ID', value: 'id'},
            {label: 'Quote ID', value: 'quoteId'},
            {label: 'Payer FSP', value: 'payerFsp'},
            {label: 'Payee FSP', value: 'payeeFsp'},
            {label: 'Error', value: 'failed'},
        ],
        columns: [
            {key: 'quoteId', label: 'Quote ID'},
            {key: 'scenario', label: 'Scenario'},
            {key: 'amount', label: 'Amount'},
            {key: 'payerFsp', label: 'Payer'},
            {key: 'payeeFsp', label: 'Payee'},
            {key: 'failed', label: 'Failed'},
            {key: 'createdAt', label: 'Created At'},
            {key: 'completedAt', label: 'Completed At'},
        ],
        primaryKey: 'quoteId',
    },
    {
        key: 'inbound-transfers',
        group: 'Inbound',
        title: 'Transfers',
        menuLabel: 'Transfers',
        subtitle: 'Search inbound transfer callbacks by transfer ID and status.',
        endpoint: '/audit/inbound/transfers',
        criteriaFields: [
            {key: 'payerFsp', label: 'Payer FSP', type: 'text', placeholder: 'wallet-a'},
            {key: 'payeeFsp', label: 'Payee FSP', type: 'text', placeholder: 'switch'},
            {key: 'transferId', label: 'Transfer ID', type: 'text', placeholder: 'uuid'},
            {key: 'error', label: 'Has Error', type: 'select', options: BOOL_OPTIONS},
            {key: 'createdAtStart', label: 'Created At (Start)', type: 'datetime'},
            {key: 'createdAtEnd', label: 'Created At (End)', type: 'datetime'},
            {key: 'completedAtStart', label: 'Completed At (Start)', type: 'datetime'},
            {key: 'completedAtEnd', label: 'Completed At (End)', type: 'datetime'},
        ],
        orderColumns: [
            {label: 'Created At', value: 'createdAt'},
            {label: 'Completed At', value: 'completedAt'},
            {label: 'ID', value: 'id'},
            {label: 'Transfer ID', value: 'transferId'},
            {label: 'Payer FSP', value: 'payerFsp'},
            {label: 'Payee FSP', value: 'payeeFsp'},
            {label: 'Error', value: 'failed'},
        ],
        columns: [
            {key: 'transferId', label: 'Transfer ID'},
            {key: 'payerFsp', label: 'Payer'},
            {key: 'payeeFsp', label: 'Payee'},
            {key: 'failed', label: 'Failed'},
            {key: 'createdAt', label: 'Created At'},
            {key: 'completedAt', label: 'Completed At'},
        ],
        primaryKey: 'transferId',
    },
    {
        key: 'outbound-parties',
        group: 'Outbound',
        title: 'Parties',
        menuLabel: 'Parties',
        subtitle: 'Audit party lookups initiated by outbound flows.',
        endpoint: '/audit/outbound/parties',
        criteriaFields: [
            {key: 'payerFsp', label: 'Payer FSP', type: 'text', placeholder: 'wallet-a'},
            {key: 'payeeFsp', label: 'Payee FSP', type: 'text', placeholder: 'switch'},
            {key: 'partyIdType', label: 'Party ID Type', type: 'select', options: PARTY_ID_TYPE_OPTIONS},
            {key: 'partyId', label: 'Party ID', type: 'text', placeholder: '959420000111'},
            {key: 'subId', label: 'Sub ID', type: 'text', placeholder: 'optional (use "null" to query null)'},
            {key: 'error', label: 'Has Error', type: 'select', options: BOOL_OPTIONS},
            {key: 'createdAtStart', label: 'Created At (Start)', type: 'datetime'},
            {key: 'createdAtEnd', label: 'Created At (End)', type: 'datetime'},
            {key: 'completedAtStart', label: 'Completed At (Start)', type: 'datetime'},
            {key: 'completedAtEnd', label: 'Completed At (End)', type: 'datetime'},
        ],
        orderColumns: [
            {label: 'Created At', value: 'createdAt'},
            {label: 'Completed At', value: 'completedAt'},
            {label: 'ID', value: 'id'},
            {label: 'Party ID', value: 'partyId'},
            {label: 'Payer FSP', value: 'payerFsp'},
            {label: 'Payee FSP', value: 'payeeFsp'},
            {label: 'Error', value: 'failed'},
        ],
        columns: [
            {key: 'payerFsp', label: 'Payer'},
            {key: 'payeeFsp', label: 'Payee'},
            {key: 'partyIdType', label: 'Party Type'},
            {key: 'partyId', label: 'Party ID'},
            {key: 'subId', label: 'Sub ID'},
            {key: 'failed', label: 'Failed'},
            {key: 'createdAt', label: 'Created At'},
            {key: 'completedAt', label: 'Completed At'},
        ],
        primaryKey: 'partyId',
    },
    {
        key: 'outbound-quotes',
        group: 'Outbound',
        title: 'Quotes',
        menuLabel: 'Quotes',
        subtitle: 'Explore outbound quote requests and returned quote callbacks.',
        endpoint: '/audit/outbound/quotes',
        criteriaFields: [
            {key: 'payerFsp', label: 'Payer FSP', type: 'text', placeholder: 'wallet-a'},
            {key: 'payeeFsp', label: 'Payee FSP', type: 'text', placeholder: 'switch'},
            {key: 'quoteId', label: 'Quote ID', type: 'text', placeholder: 'uuid'},
            {key: 'scenario', label: 'Scenario', type: 'text', placeholder: 'TRANSFER'},
            {key: 'subScenario', label: 'Sub Scenario', type: 'text', placeholder: 'scheme-specific'},
            {key: 'error', label: 'Has Error', type: 'select', options: BOOL_OPTIONS},
            {key: 'createdAtStart', label: 'Created At (Start)', type: 'datetime'},
            {key: 'createdAtEnd', label: 'Created At (End)', type: 'datetime'},
            {key: 'completedAtStart', label: 'Completed At (Start)', type: 'datetime'},
            {key: 'completedAtEnd', label: 'Completed At (End)', type: 'datetime'},
        ],
        orderColumns: [
            {label: 'Created At', value: 'createdAt'},
            {label: 'Completed At', value: 'completedAt'},
            {label: 'ID', value: 'id'},
            {label: 'Quote ID', value: 'quoteId'},
            {label: 'Payer FSP', value: 'payerFsp'},
            {label: 'Payee FSP', value: 'payeeFsp'},
            {label: 'Error', value: 'failed'},
        ],
        columns: [
            {key: 'quoteId', label: 'Quote ID'},
            {key: 'scenario', label: 'Scenario'},
            {key: 'amount', label: 'Amount'},
            {key: 'payerFsp', label: 'Payer'},
            {key: 'payeeFsp', label: 'Payee'},
            {key: 'failed', label: 'Failed'},
            {key: 'createdAt', label: 'Created At'},
            {key: 'completedAt', label: 'Completed At'},
        ],
        primaryKey: 'quoteId',
    },
    {
        key: 'outbound-transfers',
        group: 'Outbound',
        title: 'Transfers',
        menuLabel: 'Transfers',
        subtitle: 'Inspect outbound transfer executions, responses, and failures.',
        endpoint: '/audit/outbound/transfers',
        criteriaFields: [
            {key: 'payerFsp', label: 'Payer FSP', type: 'text', placeholder: 'wallet-a'},
            {key: 'payeeFsp', label: 'Payee FSP', type: 'text', placeholder: 'switch'},
            {key: 'transferId', label: 'Transfer ID', type: 'text', placeholder: 'uuid'},
            {key: 'error', label: 'Has Error', type: 'select', options: BOOL_OPTIONS},
            {key: 'createdAtStart', label: 'Created At (Start)', type: 'datetime'},
            {key: 'createdAtEnd', label: 'Created At (End)', type: 'datetime'},
            {key: 'completedAtStart', label: 'Completed At (Start)', type: 'datetime'},
            {key: 'completedAtEnd', label: 'Completed At (End)', type: 'datetime'},
        ],
        orderColumns: [
            {label: 'Created At', value: 'createdAt'},
            {label: 'Completed At', value: 'completedAt'},
            {label: 'ID', value: 'id'},
            {label: 'Transfer ID', value: 'transferId'},
            {label: 'Payer FSP', value: 'payerFsp'},
            {label: 'Payee FSP', value: 'payeeFsp'},
            {label: 'Error', value: 'failed'},
        ],
        columns: [
            {key: 'transferId', label: 'Transfer ID'},
            {key: 'payerFsp', label: 'Payer'},
            {key: 'payeeFsp', label: 'Payee'},
            {key: 'failed', label: 'Failed'},
            {key: 'createdAt', label: 'Created At'},
            {key: 'completedAt', label: 'Completed At'},
        ],
        primaryKey: 'transferId',
    },
];

export const VIEW_BY_KEY = Object.fromEntries(
    VIEW_DEFINITIONS.map((view: ViewDefinition): [ViewKey, ViewDefinition] => [view.key, view]),
) as Record<ViewKey, ViewDefinition>;
