import type {ViewDefinition, ViewKey, SelectOption} from './types';
import {TransactionScenario} from '../../../../shared/fspiop/dto/transaction-scenario';

const BOOL_OPTIONS: SelectOption[] = [
    {label: '(Any)', value: ''},
    {label: 'True', value: 'true'},
    {label: 'False', value: 'false'},
];

const PARTY_ID_TYPE_OPTIONS: SelectOption[] = [
    {label: '(Any)', value: ''},
    {label: 'MSISDN', value: 'MSISDN'},
    {label: 'EMAIL', value: 'EMAIL'},
    {label: 'PERSONAL_ID', value: 'PERSONAL_ID'},
    {label: 'BUSINESS', value: 'BUSINESS'},
    {label: 'DEVICE', value: 'DEVICE'},
    {label: 'ACCOUNT_ID', value: 'ACCOUNT_ID'},
    {label: 'IBAN', value: 'IBAN'},
    {label: 'ALIAS', value: 'ALIAS'},
];

const TRANSACTION_SCENARIO_OPTIONS: SelectOption[] = [
    {label: '(Any)', value: ''},
    ...Object.values(TransactionScenario).map((scenario: TransactionScenario): SelectOption => ({
        label: scenario,
        value: scenario,
    })),
];

export const VIEW_DEFINITIONS: ViewDefinition[] = [
    {
        key: 'hub-add-currency',
        group: 'Hub',
        title: 'Add Currency',
        menuLabel: 'Add Currency',
        subtitle: 'Provision Hub settlement and reconciliation accounts plus the deferred net settlement model for a currency.',
        endpoint: '/hub/currency',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'id',
    },
    {
        key: 'hub-list-participants',
        group: 'Hub',
        title: 'List Participants',
        menuLabel: 'List Participants',
        subtitle: 'Review the participants currently registered in central ledger, including their status and currencies.',
        endpoint: '/participant/list',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'name',
    },
    {
        key: 'hub-add-signing-keys',
        group: 'Hub',
        title: 'Add Signing Keys',
        menuLabel: 'Add Signing Keys',
        subtitle: 'Create or update the JWS signing key pair for Hub.',
        endpoint: '/hub/signing-keys',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'id',
    },
    {
        key: 'participant-onboarding',
        group: 'Participant',
        title: 'Onboard FSP',
        menuLabel: 'Onboard FSP',
        subtitle: 'Provision a new FSP with its endpoint, signing keys, and supported currencies.',
        endpoint: '/participant/onboard',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'id',
    },
    {
        key: 'participant-add-new-currency',
        group: 'Participant',
        title: 'Add Currency',
        menuLabel: 'Add Currency',
        subtitle: 'Enable one or more additional currencies for an existing participant.',
        endpoint: '/participant/currency',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'id',
    },
    {
        key: 'participant-register-endpoint',
        group: 'Participant',
        title: 'Register Endpoint',
        menuLabel: 'Register Endpoint',
        subtitle: 'Register or replace the callback endpoint configuration for an existing participant.',
        endpoint: '/participant/endpoint',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'id',
    },
    {
        key: 'participant-add-signing-keys',
        group: 'Participant',
        title: 'Add Signing Keys',
        menuLabel: 'Add Signing Keys',
        subtitle: 'Create or update the JWS signing key pair for a participant by name.',
        endpoint: '/participant/signing-keys',
        criteriaFields: [],
        orderColumns: [],
        columns: [],
        primaryKey: 'id',
    },
    {
        key: 'transactions',
        group: 'Audit',
        title: 'Find Transactions',
        menuLabel: 'Find Transactions',
        subtitle: 'Search audited transactions across parties, quotes, and transfers from one place.',
        endpoint: '/audit/transactions',
        criteriaFields: [
            {key: 'payerFsp', label: 'Payer FSP', type: 'text', placeholder: '(Any)'},
            {key: 'payeeFsp', label: 'Payee FSP', type: 'text', placeholder: '(Any)'},
            {key: 'payerIdType', label: 'Payer ID Type', type: 'select', options: PARTY_ID_TYPE_OPTIONS},
            {key: 'payerId', label: 'Payer ID', type: 'text', placeholder: '(Any)'},
            {key: 'payerSubId', label: 'Payer Sub ID', type: 'text', placeholder: '(Any)'},
            {key: 'payeeIdType', label: 'Payee ID Type', type: 'select', options: PARTY_ID_TYPE_OPTIONS},
            {key: 'payeeId', label: 'Payee ID', type: 'text', placeholder: '(Any)'},
            {key: 'payeeSubId', label: 'Payee Sub ID', type: 'text', placeholder: '(Any)'},
            {key: 'transferType', label: 'Transaction Type', type: 'select', options: TRANSACTION_SCENARIO_OPTIONS},
            {key: 'subScenario', label: 'Sub Scenario', type: 'text', placeholder: '(Any)'},
            {key: 'error', label: 'Has Error', type: 'select', options: BOOL_OPTIONS},
            {key: 'dispute', label: 'Possible Dispute', type: 'select', options: BOOL_OPTIONS},
            {key: 'transactionStartAtStart', label: 'Transaction Start (Start)', type: 'datetime'},
            {key: 'transactionStartAtEnd', label: 'Transaction Start (End)', type: 'datetime'},
            {key: 'transactionCompletedAtStart', label: 'Transaction Completed (Start)', type: 'datetime'},
            {key: 'transactionCompletedAtEnd', label: 'Transaction Completed (End)', type: 'datetime'},
        ],
        orderColumns: [
            {label: 'Transaction Start', value: 'transactionStartAt'},
            {label: 'Transaction Completed', value: 'transactionCompletedAt'},
            {label: 'ID', value: 'id'},
            {label: 'Correlation ID', value: 'correlationId'},
            {label: 'Payer FSP', value: 'payerFsp'},
            {label: 'Payee FSP', value: 'payeeFsp'},
            {label: 'Transfer Type', value: 'transferType'},
            {label: 'Error', value: 'failed'},
            {label: 'Dispute', value: 'dispute'},
        ],
        columns: [
            {key: 'correlationId', label: 'Transfer ID'},
            {key: 'payer', label: 'Payer'},
            {key: 'payee', label: 'Payee'},
            {key: 'transferType', label: 'Scenario'},
            {key: 'amount', label: 'Amount'},
            {key: 'transactionStartAt', label: 'Date/Time'},
            {key: 'status', label: 'Status'},
            {key: 'details', label: 'Details'},
        ],
        primaryKey: 'correlationId',
    },
];

export const VIEW_BY_KEY = Object.fromEntries(
    VIEW_DEFINITIONS.map((view: ViewDefinition): [ViewKey, ViewDefinition] => [view.key, view]),
) as Record<ViewKey, ViewDefinition>;
