#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-2026 ThitsaWorks Pte. Ltd.
#
# The CA root ceremony against AWS CloudHSM. Run ONCE per deployment.
#
#   ./ceremony-hsm.sh
#
# This is the PKCS#11 counterpart of ../../kms/scripts/ceremony-kms.js and the
# production counterpart of ../../local/scripts/ceremony-local.sh. All three do the
# same thing and differ only in who holds the root key:
#
#   local        SoftHSM2          PKCS#11 C_Sign     rehearsal only
#   kms          AWS KMS           kms:Sign           KMS-backed profile
#   hsm (this)   AWS CloudHSM      PKCS#11 C_Sign     HSM-backed profile
#
# CloudHSM is NOT a certificate authority. It will not issue a certificate; it signs
# a digest and nothing more. OpenSSL builds the X.509 here and the HSM only signs --
# which is why Vault needs no HSM integration of any kind and no Enterprise licence.
#
# The two roots MUST stay separate. Merging them would make a DFSP's client
# certificate trusted by the Hub.
#
# ONE ROOT PER CRYPTO USER. CloudHSM has a single token, so unlike SoftHSM the two
# roots cannot be separated by token. They are separated by OWNER instead: each root
# is generated by its own crypto user, so a compromised ceremony credential yields
# one trust domain, not both.
#
# NEITHER ceremony credential ever goes into Vault. The root keys must be
# unreachable from every running service. Custodians hold these and nothing else
# does -- that is the whole point of rooting in hardware.
set -euo pipefail

# ---------------------------------------------------------------------------
# Settings
# ---------------------------------------------------------------------------

# Outside the repository on purpose: this directory holds the ceremony's working
# files, and nothing here should be one `git add -A` away from being committed.
HERE=${CEREMONY_DIR:-${TMPDIR:-/tmp}/pivotal-ceremony-hsm}

# CloudHSM's PKCS#11 library, installed by the CloudHSM client package.
MOD=${PKCS11_MODULE:-/opt/cloudhsm/lib/libcloudhsm_pkcs11.so}

# Where the OpenSSL pkcs11 engine lives. See the note under "Engines" below.
export OPENSSL_ENGINES=${OPENSSL_ENGINES:-/usr/lib/x86_64-linux-gnu/engines-3}
export PKCS11_MODULE_PATH=${PKCS11_MODULE_PATH:-$MOD}

VAULT_NS=${VAULT_NS:-vault}
VAULT_POD=${VAULT_POD:-vault-0}
VAULT_TOKEN=${VAULT_TOKEN:-}

ROOT_DAYS=${ROOT_DAYS:-3650}
INTER_DAYS=${INTER_DAYS:-1825}

# ---------------------------------------------------------------------------
# Engines
# ---------------------------------------------------------------------------
# This script drives CloudHSM through the generic libp11 `pkcs11` engine, the same
# engine ceremony-local.sh uses against SoftHSM. That is deliberate: one code path
# for both, so the rehearsal genuinely rehearses this.
#
# AWS also ships its own OpenSSL Dynamic Engine for CloudHSM. If the generic engine
# will not load your cluster, switch OPENSSL_ENGINE_ID to AWS's and re-run -- the
# certificate contents are identical either way, only the plumbing differs.
ENGINE_ID=${OPENSSL_ENGINE_ID:-pkcs11}

# ---------------------------------------------------------------------------
# Credentials -- prompted, never in argv and never in a file
# ---------------------------------------------------------------------------
# A password on the command line lands in shell history and in the process list.
prompt_cu() {
  local var=$1 prompt=$2 user pass
  read -r -p "  $prompt crypto user: " user
  read -r -s -p "  $prompt password: " pass
  echo
  printf -v "$var" '%s:%s' "$user" "$pass"
}

echo "CloudHSM CA root ceremony"
echo "Two trust domains, one crypto user each. Credentials are prompted, not stored."
echo

CU_HUB=${CU_HUB_PIN:-}
CU_DFSP=${CU_DFSP_PIN:-}
[ -n "$CU_HUB" ]  || prompt_cu CU_HUB  "Hub-client root"
[ -n "$CU_DFSP" ] || prompt_cu CU_DFSP "DFSP-facing root"

if [ "$CU_HUB" = "$CU_DFSP" ]; then
  echo "REFUSING: both roots would be owned by the same crypto user." >&2
  echo "That merges the two trust domains' blast radius. Use one CU per domain." >&2
  exit 1
fi

if [ -z "$VAULT_TOKEN" ]; then
  read -r -s -p "  Vault token: " VAULT_TOKEN
  echo
fi

mkdir -p "$HERE/out"
chmod 700 "$HERE"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

v() {
  kubectl exec -n "$VAULT_NS" -i "$VAULT_POD" -- sh -c \
    "export VAULT_ADDR=http://127.0.0.1:8200 VAULT_TOKEN=$VAULT_TOKEN; $1"
}

# Does a key with this label already exist? Re-running the ceremony must never
# quietly mint a second root -- two roots with one label is an ambiguity the engine
# resolves by returning nothing useful, and it is very hard to see.
key_exists() {
  local pin=$1 label=$2
  CLOUDHSM_ROLE=crypto-user CLOUDHSM_PIN="$pin" \
    cloudhsm-cli key list --filter "attr.label=$label" 2>/dev/null \
      | grep -qE "(^|[^A-Za-z0-9_-])${label}([^A-Za-z0-9_-]|$)"
}

# ---------------------------------------------------------------------------
# The ceremony, run once per trust domain
# ---------------------------------------------------------------------------

ceremony() {
  local mount=$1 cn=$2 pin=$3 role_args=$4 role_name=$5
  local label="${mount}-root"
  local out="$HERE/out/$mount"

  mkdir -p "$out"
  echo
  echo "── $cn ──────────────────────────────────────────"

  # 1. Root keypair, generated INSIDE the HSM.
  #
  #    extractable=false is the line that makes this the HSM-backed profile. It is
  #    a creation-time property: no backend can retrofit it, so a key generated
  #    without it is not fixable, only replaceable.
  if key_exists "$pin" "$label"; then
    echo "  root keypair already present — not regenerating"
  else
    CLOUDHSM_ROLE=crypto-user CLOUDHSM_PIN="$pin" \
      cloudhsm-cli key generate-asymmetric-pair rsa \
        --public-label  "${label}-pub" \
        --private-label "$label" \
        --modulus-size-bits 2048 \
        --public-exponent 65537 \
        --private-attributes sign=true extractable=false >/dev/null
    echo "  root keypair generated in CloudHSM (non-extractable)"
  fi

  # The PKCS#11 URI the engine resolves. CloudHSM presents one token, so the object
  # label is what selects the key -- unlike SoftHSM, where each domain had a token.
  local keyuri="pkcs11:object=${label};type=private;pin-value=${pin}"

  # 2. Self-signed root. OpenSSL builds the certificate; the HSM only signs it.
  cat > "$out/root.cnf" <<EOF
[req]
distinguished_name=dn
x509_extensions=v3
prompt=no
[dn]
O=ThitsaWorks
CN=$cn Root
[v3]
basicConstraints=critical,CA:TRUE
keyUsage=critical,keyCertSign,cRLSign
subjectKeyIdentifier=hash
EOF
  openssl req -new -x509 -days "$ROOT_DAYS" \
    -engine "$ENGINE_ID" -keyform engine -key "$keyuri" \
    -sha256 -config "$out/root.cnf" -out "$out/root.pem"
  echo "  root certificate: $(openssl x509 -in "$out/root.pem" -noout -subject | sed 's/subject=//')"

  # 3. Vault generates the intermediate keypair. The private half is created in
  #    Vault and stays there -- it is never exported and never reaches this script.
  v "vault secrets disable $mount 2>/dev/null || true" >/dev/null
  v "vault secrets enable -path=$mount -max-lease-ttl=43800h pki" >/dev/null
  v "vault write -field=csr $mount/intermediate/generate/internal \
       common_name='$cn Intermediate' key_bits=2048" > "$out/inter.csr"
  echo "  intermediate CSR generated in Vault"

  # 4. The root signs the intermediate. This happens exactly once, here, and is the
  #    only time either root key is used outside a revocation.
  cat > "$out/inter.ext" <<EOF
basicConstraints=critical,CA:TRUE,pathlen:0
keyUsage=critical,keyCertSign,cRLSign
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid:always
EOF
  openssl x509 -req -engine "$ENGINE_ID" -CAkeyform engine -CAkey "$keyuri" \
    -CA "$out/root.pem" -in "$out/inter.csr" -set_serial 2 -days "$INTER_DAYS" \
    -sha256 -extfile "$out/inter.ext" -out "$out/inter.pem"
  echo "  intermediate signed by the HSM-held root"

  # 5. Signed intermediate back into Vault.
  v "cat > /tmp/i.crt; vault write $mount/intermediate/set-signed certificate=@/tmp/i.crt" \
    < "$out/inter.pem" >/dev/null
  echo "  intermediate installed in Vault mount '$mount'"

  # 6. Put the issuing role back.
  #
  #    Step 3 disables and re-enables the mount, which destroys every role on it. A
  #    ceremony that does not restore what it removed leaves cert-manager failing
  #    with "unknown role" -- and it fails at the next renewal, not now, so nobody
  #    connects it to the ceremony.
  #
  #    use_csr_common_name=false is load-bearing on the DFSP role: Vault's `sign`
  #    endpoint defaults to taking the subject from the submitted CSR, which would
  #    let a DFSP request a certificate naming any other participant.
  v "vault write $mount/roles/$role_name $role_args" >/dev/null
  echo "  issuing role restored: $mount/roles/$role_name"

  # 7. An empty root CRL, signed now.
  #
  #    Revoking an intermediate needs a root-signed CRL, and producing one means
  #    using the root key again. Far cheaper to prove it works while the ceremony is
  #    open than to discover during an incident that it does not.
  mkdir -p "$out/ca"
  : > "$out/ca/index.txt"
  echo 1000 > "$out/ca/crlnumber"
  cat > "$out/ca/ca.cnf" <<EOF
[ca]
default_ca=CA_default
[CA_default]
database=$out/ca/index.txt
crlnumber=$out/ca/crlnumber
default_md=sha256
default_crl_days=30
EOF
  if openssl ca -gencrl -config "$out/ca/ca.cnf" \
       -engine "$ENGINE_ID" -keyform engine -keyfile "$keyuri" \
       -cert "$out/root.pem" -out "$out/root.crl"; then
    echo "  root CRL signed: $(openssl crl -in "$out/root.crl" -noout -lastupdate | sed 's/.*=//')"
  else
    echo "  root CRL: FAILED — fix this now, not during an incident" >&2
    return 1
  fi

  # 8. Prove the chain before anyone relies on it.
  if openssl verify -CAfile "$out/root.pem" -partial_chain "$out/inter.pem" >/dev/null 2>&1; then
    echo "  chain verified: intermediate → root"
  else
    echo "  chain verification FAILED" >&2
    return 1
  fi
}

ceremony pki_hub_client "Pivotal Hub Client CA" "$CU_HUB" \
  "allow_any_name=true enforce_hostnames=false client_flag=true server_flag=false \
   key_bits=2048 max_ttl=2160h ttl=2160h organization='ThitsaWorks' ou='Pivotal' \
   no_store=true require_cn=false use_csr_common_name=false use_csr_sans=false" \
  pivotal-client

ceremony pki_dfsp "Pivotal DFSP-Facing CA" "$CU_DFSP" \
  "allow_any_name=true enforce_hostnames=false client_flag=true server_flag=false \
   key_bits=2048 max_ttl=8760h ttl=8760h organization='ThitsaWorks' ou='DFSP' \
   no_store=true require_cn=true use_csr_common_name=false use_csr_sans=false" \
  dfsp-client

echo
echo "Done. Both roots are in CloudHSM and cannot be exported."
echo "Public certificates and CRLs: $HERE/out/"
echo
echo "Next:"
echo "  - distribute pki_dfsp/root.pem to the gateway trust anchor"
echo "  - register pki_hub_client's chain with MCM"
echo "  - store both ceremony crypto-user credentials with their custodians"
echo "  - destroy this working directory once the certificates are distributed:"
echo "      rm -rf $HERE"
