{{- if .Values.nats.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  labels:
    {{- include "pivotal-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  replicas: {{ .Values.nats.replicaCount }}
  selector:
    matchLabels:
      {{- include "pivotal-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nats
  template:
    metadata:
      labels:
        {{- include "pivotal-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nats
    spec:
      containers:
        - name: nats
          image: "{{ .Values.nats.image.repository }}:{{ .Values.nats.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command:
            {{- toYaml .Values.nats.command | nindent 12 }}
          ports:
            - name: client
              containerPort: {{ .Values.nats.service.clientPort }}
              protocol: TCP
            - name: monitor
              containerPort: {{ .Values.nats.service.monitorPort }}
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    {{- include "pivotal-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  type: {{ .Values.nats.service.type }}
  selector:
    {{- include "pivotal-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nats
  ports:
    - name: client
      port: {{ .Values.nats.service.clientPort }}
      targetPort: client
      protocol: TCP
    - name: monitor
      port: {{ .Values.nats.service.monitorPort }}
      targetPort: monitor
      protocol: TCP
{{- end }}
