/* tslint:disable */
/* eslint-disable */
/**
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BulkTransfersIDPutResponse } from '../model';
// @ts-ignore
import type { BulkTransfersPostRequest } from '../model';
// @ts-ignore
import type { ErrorInformationObject } from '../model';
// @ts-ignore
import type { ErrorInformationResponse } from '../model';
/**
 * BulkTransfersApi - axios parameter creator
 * @export
 */
export const BulkTransfersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * The HTTP request `GET /bulkTransfers/{ID}` is used to get information regarding a bulk transfer created or requested earlier. The `{ID}` in the URI should contain the `bulkTransferId` that was used for the creation of the bulk transfer.
         * @summary Retrieve bulk transfer information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkTransferByID: async (iD: string, contentType: string, date: string, fSPIOPSource: string, accept: string, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('bulkTransferByID', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('bulkTransferByID', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('bulkTransferByID', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('bulkTransferByID', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'accept' is not null or undefined
            assertParamExists('bulkTransferByID', 'accept', accept)
            const localVarPath = `/bulkTransfers/{ID}`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The HTTP request `POST /bulkTransfers` is used to request the creation of a bulk transfer in the server.
         * @summary Perform bulk transfer
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {BulkTransfersPostRequest} bulkTransfersPostRequest Details of the bulk transfer to be created.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkTransfers: async (accept: string, contentType: string, date: string, fSPIOPSource: string, bulkTransfersPostRequest: BulkTransfersPostRequest, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accept' is not null or undefined
            assertParamExists('bulkTransfers', 'accept', accept)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('bulkTransfers', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('bulkTransfers', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('bulkTransfers', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'bulkTransfersPostRequest' is not null or undefined
            assertParamExists('bulkTransfers', 'bulkTransfersPostRequest', bulkTransfersPostRequest)
            const localVarPath = `/bulkTransfers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkTransfersPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The callback `PUT /bulkTransfers/{ID}` is used to inform the client of a requested or created bulk transfer. The `{ID}` in the URI should contain the `bulkTransferId` that was used for the creation of the bulk transfer (`POST /bulkTransfers`), or the `{ID}` that was used in the `GET /bulkTransfers/{ID}` request.
         * @summary Return bulk transfer information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {BulkTransfersIDPutResponse} bulkTransfersIDPutResponse Bulk transfer information returned.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkTransfersByIDPut: async (iD: string, contentType: string, date: string, fSPIOPSource: string, bulkTransfersIDPutResponse: BulkTransfersIDPutResponse, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, contentLength?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('bulkTransfersByIDPut', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('bulkTransfersByIDPut', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('bulkTransfersByIDPut', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('bulkTransfersByIDPut', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'bulkTransfersIDPutResponse' is not null or undefined
            assertParamExists('bulkTransfersByIDPut', 'bulkTransfersIDPutResponse', bulkTransfersIDPutResponse)
            const localVarPath = `/bulkTransfers/{ID}`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkTransfersIDPutResponse, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * If the server is unable to find or create a bulk transfer, or another processing error occurs, the error callback `PUT /bulkTransfers/{ID}/error` is used. The `{ID}` in the URI should contain the `bulkTransferId` that was used for the creation of the bulk transfer (`POST /bulkTransfers`), or the `{ID}` that was used in the `GET /bulkTransfers/{ID}` request.
         * @summary Return bulk transfer information error
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {ErrorInformationObject} errorInformationObject Details of the error returned.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkTransfersErrorByID: async (iD: string, contentType: string, date: string, fSPIOPSource: string, errorInformationObject: ErrorInformationObject, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('bulkTransfersErrorByID', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('bulkTransfersErrorByID', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('bulkTransfersErrorByID', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('bulkTransfersErrorByID', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'errorInformationObject' is not null or undefined
            assertParamExists('bulkTransfersErrorByID', 'errorInformationObject', errorInformationObject)
            const localVarPath = `/bulkTransfers/{ID}/error`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(errorInformationObject, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BulkTransfersApi - functional programming interface
 * @export
 */
export const BulkTransfersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BulkTransfersApiAxiosParamCreator(configuration)
    return {
        /**
         * The HTTP request `GET /bulkTransfers/{ID}` is used to get information regarding a bulk transfer created or requested earlier. The `{ID}` in the URI should contain the `bulkTransferId` that was used for the creation of the bulk transfer.
         * @summary Retrieve bulk transfer information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkTransferByID(iD: string, contentType: string, date: string, fSPIOPSource: string, accept: string, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkTransferByID(iD, contentType, date, fSPIOPSource, accept, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BulkTransfersApi.bulkTransferByID']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The HTTP request `POST /bulkTransfers` is used to request the creation of a bulk transfer in the server.
         * @summary Perform bulk transfer
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {BulkTransfersPostRequest} bulkTransfersPostRequest Details of the bulk transfer to be created.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkTransfers(accept: string, contentType: string, date: string, fSPIOPSource: string, bulkTransfersPostRequest: BulkTransfersPostRequest, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkTransfers(accept, contentType, date, fSPIOPSource, bulkTransfersPostRequest, contentLength, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BulkTransfersApi.bulkTransfers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The callback `PUT /bulkTransfers/{ID}` is used to inform the client of a requested or created bulk transfer. The `{ID}` in the URI should contain the `bulkTransferId` that was used for the creation of the bulk transfer (`POST /bulkTransfers`), or the `{ID}` that was used in the `GET /bulkTransfers/{ID}` request.
         * @summary Return bulk transfer information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {BulkTransfersIDPutResponse} bulkTransfersIDPutResponse Bulk transfer information returned.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkTransfersByIDPut(iD: string, contentType: string, date: string, fSPIOPSource: string, bulkTransfersIDPutResponse: BulkTransfersIDPutResponse, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, contentLength?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkTransfersByIDPut(iD, contentType, date, fSPIOPSource, bulkTransfersIDPutResponse, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, contentLength, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BulkTransfersApi.bulkTransfersByIDPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * If the server is unable to find or create a bulk transfer, or another processing error occurs, the error callback `PUT /bulkTransfers/{ID}/error` is used. The `{ID}` in the URI should contain the `bulkTransferId` that was used for the creation of the bulk transfer (`POST /bulkTransfers`), or the `{ID}` that was used in the `GET /bulkTransfers/{ID}` request.
         * @summary Return bulk transfer information error
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {ErrorInformationObject} errorInformationObject Details of the error returned.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkTransfersErrorByID(iD: string, contentType: string, date: string, fSPIOPSource: string, errorInformationObject: ErrorInformationObject, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkTransfersErrorByID(iD, contentType, date, fSPIOPSource, errorInformationObject, contentLength, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BulkTransfersApi.bulkTransfersErrorByID']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BulkTransfersApi - factory interface
 * @export
 */
export const BulkTransfersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BulkTransfersApiFp(configuration)
    return {
        /**
         * The HTTP request `GET /bulkTransfers/{ID}` is used to get information regarding a bulk transfer created or requested earlier. The `{ID}` in the URI should contain the `bulkTransferId` that was used for the creation of the bulk transfer.
         * @summary Retrieve bulk transfer information
         * @param {BulkTransfersApiBulkTransferByIDRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkTransferByID(requestParameters: BulkTransfersApiBulkTransferByIDRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.bulkTransferByID(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.accept, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(axios, basePath));
        },
        /**
         * The HTTP request `POST /bulkTransfers` is used to request the creation of a bulk transfer in the server.
         * @summary Perform bulk transfer
         * @param {BulkTransfersApiBulkTransfersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkTransfers(requestParameters: BulkTransfersApiBulkTransfersRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.bulkTransfers(requestParameters.accept, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.bulkTransfersPostRequest, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(axios, basePath));
        },
        /**
         * The callback `PUT /bulkTransfers/{ID}` is used to inform the client of a requested or created bulk transfer. The `{ID}` in the URI should contain the `bulkTransferId` that was used for the creation of the bulk transfer (`POST /bulkTransfers`), or the `{ID}` that was used in the `GET /bulkTransfers/{ID}` request.
         * @summary Return bulk transfer information
         * @param {BulkTransfersApiBulkTransfersByIDPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkTransfersByIDPut(requestParameters: BulkTransfersApiBulkTransfersByIDPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.bulkTransfersByIDPut(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.bulkTransfersIDPutResponse, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, requestParameters.contentLength, options).then((request) => request(axios, basePath));
        },
        /**
         * If the server is unable to find or create a bulk transfer, or another processing error occurs, the error callback `PUT /bulkTransfers/{ID}/error` is used. The `{ID}` in the URI should contain the `bulkTransferId` that was used for the creation of the bulk transfer (`POST /bulkTransfers`), or the `{ID}` that was used in the `GET /bulkTransfers/{ID}` request.
         * @summary Return bulk transfer information error
         * @param {BulkTransfersApiBulkTransfersErrorByIDRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkTransfersErrorByID(requestParameters: BulkTransfersApiBulkTransfersErrorByIDRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.bulkTransfersErrorByID(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.errorInformationObject, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for bulkTransferByID operation in BulkTransfersApi.
 * @export
 * @interface BulkTransfersApiBulkTransferByIDRequest
 */
export interface BulkTransfersApiBulkTransferByIDRequest {
    /**
     * The identifier value.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransferByID
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransferByID
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransferByID
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof BulkTransfersApiBulkTransferByID
     */
    readonly fSPIOPSource: string

    /**
     * The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransferByID
     */
    readonly accept: string

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransferByID
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransferByID
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransferByID
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransferByID
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof BulkTransfersApiBulkTransferByID
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof BulkTransfersApiBulkTransferByID
     */
    readonly fSPIOPHTTPMethod?: string
}

/**
 * Request parameters for bulkTransfers operation in BulkTransfersApi.
 * @export
 * @interface BulkTransfersApiBulkTransfersRequest
 */
export interface BulkTransfersApiBulkTransfersRequest {
    /**
     * The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfers
     */
    readonly accept: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfers
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfers
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfers
     */
    readonly fSPIOPSource: string

    /**
     * Details of the bulk transfer to be created.
     * @type {BulkTransfersPostRequest}
     * @memberof BulkTransfersApiBulkTransfers
     */
    readonly bulkTransfersPostRequest: BulkTransfersPostRequest

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof BulkTransfersApiBulkTransfers
     */
    readonly contentLength?: number

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfers
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfers
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfers
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfers
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfers
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfers
     */
    readonly fSPIOPHTTPMethod?: string
}

/**
 * Request parameters for bulkTransfersByIDPut operation in BulkTransfersApi.
 * @export
 * @interface BulkTransfersApiBulkTransfersByIDPutRequest
 */
export interface BulkTransfersApiBulkTransfersByIDPutRequest {
    /**
     * The identifier value.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersByIDPut
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersByIDPut
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersByIDPut
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersByIDPut
     */
    readonly fSPIOPSource: string

    /**
     * Bulk transfer information returned.
     * @type {BulkTransfersIDPutResponse}
     * @memberof BulkTransfersApiBulkTransfersByIDPut
     */
    readonly bulkTransfersIDPutResponse: BulkTransfersIDPutResponse

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersByIDPut
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersByIDPut
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersByIDPut
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersByIDPut
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersByIDPut
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersByIDPut
     */
    readonly fSPIOPHTTPMethod?: string

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof BulkTransfersApiBulkTransfersByIDPut
     */
    readonly contentLength?: number
}

/**
 * Request parameters for bulkTransfersErrorByID operation in BulkTransfersApi.
 * @export
 * @interface BulkTransfersApiBulkTransfersErrorByIDRequest
 */
export interface BulkTransfersApiBulkTransfersErrorByIDRequest {
    /**
     * The identifier value.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersErrorByID
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersErrorByID
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersErrorByID
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersErrorByID
     */
    readonly fSPIOPSource: string

    /**
     * Details of the error returned.
     * @type {ErrorInformationObject}
     * @memberof BulkTransfersApiBulkTransfersErrorByID
     */
    readonly errorInformationObject: ErrorInformationObject

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof BulkTransfersApiBulkTransfersErrorByID
     */
    readonly contentLength?: number

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersErrorByID
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersErrorByID
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersErrorByID
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersErrorByID
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersErrorByID
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof BulkTransfersApiBulkTransfersErrorByID
     */
    readonly fSPIOPHTTPMethod?: string
}

/**
 * BulkTransfersApi - object-oriented interface
 * @export
 * @class BulkTransfersApi
 * @extends {BaseAPI}
 */
export class BulkTransfersApi extends BaseAPI {
    /**
     * The HTTP request `GET /bulkTransfers/{ID}` is used to get information regarding a bulk transfer created or requested earlier. The `{ID}` in the URI should contain the `bulkTransferId` that was used for the creation of the bulk transfer.
     * @summary Retrieve bulk transfer information
     * @param {BulkTransfersApiBulkTransferByIDRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkTransfersApi
     */
    public bulkTransferByID(requestParameters: BulkTransfersApiBulkTransferByIDRequest, options?: RawAxiosRequestConfig) {
        return BulkTransfersApiFp(this.configuration).bulkTransferByID(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.accept, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The HTTP request `POST /bulkTransfers` is used to request the creation of a bulk transfer in the server.
     * @summary Perform bulk transfer
     * @param {BulkTransfersApiBulkTransfersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkTransfersApi
     */
    public bulkTransfers(requestParameters: BulkTransfersApiBulkTransfersRequest, options?: RawAxiosRequestConfig) {
        return BulkTransfersApiFp(this.configuration).bulkTransfers(requestParameters.accept, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.bulkTransfersPostRequest, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The callback `PUT /bulkTransfers/{ID}` is used to inform the client of a requested or created bulk transfer. The `{ID}` in the URI should contain the `bulkTransferId` that was used for the creation of the bulk transfer (`POST /bulkTransfers`), or the `{ID}` that was used in the `GET /bulkTransfers/{ID}` request.
     * @summary Return bulk transfer information
     * @param {BulkTransfersApiBulkTransfersByIDPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkTransfersApi
     */
    public bulkTransfersByIDPut(requestParameters: BulkTransfersApiBulkTransfersByIDPutRequest, options?: RawAxiosRequestConfig) {
        return BulkTransfersApiFp(this.configuration).bulkTransfersByIDPut(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.bulkTransfersIDPutResponse, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, requestParameters.contentLength, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * If the server is unable to find or create a bulk transfer, or another processing error occurs, the error callback `PUT /bulkTransfers/{ID}/error` is used. The `{ID}` in the URI should contain the `bulkTransferId` that was used for the creation of the bulk transfer (`POST /bulkTransfers`), or the `{ID}` that was used in the `GET /bulkTransfers/{ID}` request.
     * @summary Return bulk transfer information error
     * @param {BulkTransfersApiBulkTransfersErrorByIDRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkTransfersApi
     */
    public bulkTransfersErrorByID(requestParameters: BulkTransfersApiBulkTransfersErrorByIDRequest, options?: RawAxiosRequestConfig) {
        return BulkTransfersApiFp(this.configuration).bulkTransfersErrorByID(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.errorInformationObject, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(this.axios, this.basePath));
    }
}

