/* tslint:disable */
/* eslint-disable */
/**
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorInformationObject } from '../model';
// @ts-ignore
import type { ErrorInformationResponse } from '../model';
// @ts-ignore
import type { FxQuotesIDPutResponse } from '../model';
// @ts-ignore
import type { FxQuotesPostRequest } from '../model';
/**
 * FxQuotesApi - axios parameter creator
 * @export
 */
export const FxQuotesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * If the FXP is unable to find or create a FX quote, or some other processing error occurs, the error callback `PUT /fxQuotes/{ID}/error` is used. The `{ID}` in the URI should contain the `conversionRequestId` that was used for the creation of the FX quote, or the `{ID}` that was used in the `GET /fxQuotes/{ID}` request.
         * @summary Return FX quote information error
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {ErrorInformationObject} errorInformationObject Details of the error returned.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxQuotesByIDAndErrorPut: async (iD: string, contentType: string, date: string, fSPIOPSource: string, errorInformationObject: ErrorInformationObject, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('fxQuotesByIDAndErrorPut', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('fxQuotesByIDAndErrorPut', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('fxQuotesByIDAndErrorPut', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('fxQuotesByIDAndErrorPut', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'errorInformationObject' is not null or undefined
            assertParamExists('fxQuotesByIDAndErrorPut', 'errorInformationObject', errorInformationObject)
            const localVarPath = `/fxQuotes/{ID}/error`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(errorInformationObject, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The HTTP request `GET /fxQuotes/{ID}` is used to request information regarding a request for quotation for a  currency conversion which the sender has previously issued. The `{ID}` in the URI should contain the `conversionRequestId` that was used for the creation of the quote.
         * @summary Retrieve FX quote information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxQuotesByIDGet: async (iD: string, contentType: string, date: string, fSPIOPSource: string, accept: string, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('fxQuotesByIDGet', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('fxQuotesByIDGet', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('fxQuotesByIDGet', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('fxQuotesByIDGet', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'accept' is not null or undefined
            assertParamExists('fxQuotesByIDGet', 'accept', accept)
            const localVarPath = `/fxQuotes/{ID}`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The callback `PUT /fxQuotes/{ID}` is used to inform the requester about the  outcome of a request for quotation for a currency conversion.  The `{ID}` in the URI should contain the `conversionRequestId` that was used for the  creation of the FX quote, or the `{ID}` that was used in the `GET /fxQuotes/{ID}` request.
         * @summary Return FX quote information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {FxQuotesIDPutResponse} fxQuotesIDPutResponse FX Quote information returned.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxQuotesByIdPut: async (iD: string, contentType: string, date: string, fSPIOPSource: string, fxQuotesIDPutResponse: FxQuotesIDPutResponse, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, contentLength?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('fxQuotesByIdPut', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('fxQuotesByIdPut', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('fxQuotesByIdPut', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('fxQuotesByIdPut', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'fxQuotesIDPutResponse' is not null or undefined
            assertParamExists('fxQuotesByIdPut', 'fxQuotesIDPutResponse', fxQuotesIDPutResponse)
            const localVarPath = `/fxQuotes/{ID}`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fxQuotesIDPutResponse, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The HTTP request `POST /fxQuotes` is used to ask an FXP to provide a quotation for a currency conversion.
         * @summary Calculate FX quote
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {FxQuotesPostRequest} fxQuotesPostRequest Details of the FX quote to be created.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxQuotesPost: async (accept: string, contentType: string, date: string, fSPIOPSource: string, fxQuotesPostRequest: FxQuotesPostRequest, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accept' is not null or undefined
            assertParamExists('fxQuotesPost', 'accept', accept)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('fxQuotesPost', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('fxQuotesPost', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('fxQuotesPost', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'fxQuotesPostRequest' is not null or undefined
            assertParamExists('fxQuotesPost', 'fxQuotesPostRequest', fxQuotesPostRequest)
            const localVarPath = `/fxQuotes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fxQuotesPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FxQuotesApi - functional programming interface
 * @export
 */
export const FxQuotesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FxQuotesApiAxiosParamCreator(configuration)
    return {
        /**
         * If the FXP is unable to find or create a FX quote, or some other processing error occurs, the error callback `PUT /fxQuotes/{ID}/error` is used. The `{ID}` in the URI should contain the `conversionRequestId` that was used for the creation of the FX quote, or the `{ID}` that was used in the `GET /fxQuotes/{ID}` request.
         * @summary Return FX quote information error
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {ErrorInformationObject} errorInformationObject Details of the error returned.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fxQuotesByIDAndErrorPut(iD: string, contentType: string, date: string, fSPIOPSource: string, errorInformationObject: ErrorInformationObject, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fxQuotesByIDAndErrorPut(iD, contentType, date, fSPIOPSource, errorInformationObject, contentLength, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FxQuotesApi.fxQuotesByIDAndErrorPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The HTTP request `GET /fxQuotes/{ID}` is used to request information regarding a request for quotation for a  currency conversion which the sender has previously issued. The `{ID}` in the URI should contain the `conversionRequestId` that was used for the creation of the quote.
         * @summary Retrieve FX quote information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fxQuotesByIDGet(iD: string, contentType: string, date: string, fSPIOPSource: string, accept: string, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fxQuotesByIDGet(iD, contentType, date, fSPIOPSource, accept, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FxQuotesApi.fxQuotesByIDGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The callback `PUT /fxQuotes/{ID}` is used to inform the requester about the  outcome of a request for quotation for a currency conversion.  The `{ID}` in the URI should contain the `conversionRequestId` that was used for the  creation of the FX quote, or the `{ID}` that was used in the `GET /fxQuotes/{ID}` request.
         * @summary Return FX quote information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {FxQuotesIDPutResponse} fxQuotesIDPutResponse FX Quote information returned.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fxQuotesByIdPut(iD: string, contentType: string, date: string, fSPIOPSource: string, fxQuotesIDPutResponse: FxQuotesIDPutResponse, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, contentLength?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fxQuotesByIdPut(iD, contentType, date, fSPIOPSource, fxQuotesIDPutResponse, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, contentLength, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FxQuotesApi.fxQuotesByIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The HTTP request `POST /fxQuotes` is used to ask an FXP to provide a quotation for a currency conversion.
         * @summary Calculate FX quote
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {FxQuotesPostRequest} fxQuotesPostRequest Details of the FX quote to be created.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fxQuotesPost(accept: string, contentType: string, date: string, fSPIOPSource: string, fxQuotesPostRequest: FxQuotesPostRequest, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fxQuotesPost(accept, contentType, date, fSPIOPSource, fxQuotesPostRequest, contentLength, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FxQuotesApi.fxQuotesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FxQuotesApi - factory interface
 * @export
 */
export const FxQuotesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FxQuotesApiFp(configuration)
    return {
        /**
         * If the FXP is unable to find or create a FX quote, or some other processing error occurs, the error callback `PUT /fxQuotes/{ID}/error` is used. The `{ID}` in the URI should contain the `conversionRequestId` that was used for the creation of the FX quote, or the `{ID}` that was used in the `GET /fxQuotes/{ID}` request.
         * @summary Return FX quote information error
         * @param {FxQuotesApiFxQuotesByIDAndErrorPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxQuotesByIDAndErrorPut(requestParameters: FxQuotesApiFxQuotesByIDAndErrorPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.fxQuotesByIDAndErrorPut(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.errorInformationObject, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(axios, basePath));
        },
        /**
         * The HTTP request `GET /fxQuotes/{ID}` is used to request information regarding a request for quotation for a  currency conversion which the sender has previously issued. The `{ID}` in the URI should contain the `conversionRequestId` that was used for the creation of the quote.
         * @summary Retrieve FX quote information
         * @param {FxQuotesApiFxQuotesByIDGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxQuotesByIDGet(requestParameters: FxQuotesApiFxQuotesByIDGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.fxQuotesByIDGet(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.accept, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(axios, basePath));
        },
        /**
         * The callback `PUT /fxQuotes/{ID}` is used to inform the requester about the  outcome of a request for quotation for a currency conversion.  The `{ID}` in the URI should contain the `conversionRequestId` that was used for the  creation of the FX quote, or the `{ID}` that was used in the `GET /fxQuotes/{ID}` request.
         * @summary Return FX quote information
         * @param {FxQuotesApiFxQuotesByIdPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxQuotesByIdPut(requestParameters: FxQuotesApiFxQuotesByIdPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.fxQuotesByIdPut(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.fxQuotesIDPutResponse, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, requestParameters.contentLength, options).then((request) => request(axios, basePath));
        },
        /**
         * The HTTP request `POST /fxQuotes` is used to ask an FXP to provide a quotation for a currency conversion.
         * @summary Calculate FX quote
         * @param {FxQuotesApiFxQuotesPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxQuotesPost(requestParameters: FxQuotesApiFxQuotesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.fxQuotesPost(requestParameters.accept, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.fxQuotesPostRequest, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for fxQuotesByIDAndErrorPut operation in FxQuotesApi.
 * @export
 * @interface FxQuotesApiFxQuotesByIDAndErrorPutRequest
 */
export interface FxQuotesApiFxQuotesByIDAndErrorPutRequest {
    /**
     * The identifier value.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDAndErrorPut
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDAndErrorPut
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDAndErrorPut
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDAndErrorPut
     */
    readonly fSPIOPSource: string

    /**
     * Details of the error returned.
     * @type {ErrorInformationObject}
     * @memberof FxQuotesApiFxQuotesByIDAndErrorPut
     */
    readonly errorInformationObject: ErrorInformationObject

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof FxQuotesApiFxQuotesByIDAndErrorPut
     */
    readonly contentLength?: number

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDAndErrorPut
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDAndErrorPut
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDAndErrorPut
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDAndErrorPut
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDAndErrorPut
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDAndErrorPut
     */
    readonly fSPIOPHTTPMethod?: string
}

/**
 * Request parameters for fxQuotesByIDGet operation in FxQuotesApi.
 * @export
 * @interface FxQuotesApiFxQuotesByIDGetRequest
 */
export interface FxQuotesApiFxQuotesByIDGetRequest {
    /**
     * The identifier value.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDGet
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDGet
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDGet
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDGet
     */
    readonly fSPIOPSource: string

    /**
     * The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDGet
     */
    readonly accept: string

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDGet
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDGet
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDGet
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDGet
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDGet
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIDGet
     */
    readonly fSPIOPHTTPMethod?: string
}

/**
 * Request parameters for fxQuotesByIdPut operation in FxQuotesApi.
 * @export
 * @interface FxQuotesApiFxQuotesByIdPutRequest
 */
export interface FxQuotesApiFxQuotesByIdPutRequest {
    /**
     * The identifier value.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIdPut
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIdPut
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIdPut
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIdPut
     */
    readonly fSPIOPSource: string

    /**
     * FX Quote information returned.
     * @type {FxQuotesIDPutResponse}
     * @memberof FxQuotesApiFxQuotesByIdPut
     */
    readonly fxQuotesIDPutResponse: FxQuotesIDPutResponse

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIdPut
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIdPut
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIdPut
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIdPut
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIdPut
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxQuotesApiFxQuotesByIdPut
     */
    readonly fSPIOPHTTPMethod?: string

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof FxQuotesApiFxQuotesByIdPut
     */
    readonly contentLength?: number
}

/**
 * Request parameters for fxQuotesPost operation in FxQuotesApi.
 * @export
 * @interface FxQuotesApiFxQuotesPostRequest
 */
export interface FxQuotesApiFxQuotesPostRequest {
    /**
     * The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesPost
     */
    readonly accept: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesPost
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesPost
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof FxQuotesApiFxQuotesPost
     */
    readonly fSPIOPSource: string

    /**
     * Details of the FX quote to be created.
     * @type {FxQuotesPostRequest}
     * @memberof FxQuotesApiFxQuotesPost
     */
    readonly fxQuotesPostRequest: FxQuotesPostRequest

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof FxQuotesApiFxQuotesPost
     */
    readonly contentLength?: number

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesPost
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesPost
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesPost
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof FxQuotesApiFxQuotesPost
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxQuotesApiFxQuotesPost
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxQuotesApiFxQuotesPost
     */
    readonly fSPIOPHTTPMethod?: string
}

/**
 * FxQuotesApi - object-oriented interface
 * @export
 * @class FxQuotesApi
 * @extends {BaseAPI}
 */
export class FxQuotesApi extends BaseAPI {
    /**
     * If the FXP is unable to find or create a FX quote, or some other processing error occurs, the error callback `PUT /fxQuotes/{ID}/error` is used. The `{ID}` in the URI should contain the `conversionRequestId` that was used for the creation of the FX quote, or the `{ID}` that was used in the `GET /fxQuotes/{ID}` request.
     * @summary Return FX quote information error
     * @param {FxQuotesApiFxQuotesByIDAndErrorPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FxQuotesApi
     */
    public fxQuotesByIDAndErrorPut(requestParameters: FxQuotesApiFxQuotesByIDAndErrorPutRequest, options?: RawAxiosRequestConfig) {
        return FxQuotesApiFp(this.configuration).fxQuotesByIDAndErrorPut(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.errorInformationObject, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The HTTP request `GET /fxQuotes/{ID}` is used to request information regarding a request for quotation for a  currency conversion which the sender has previously issued. The `{ID}` in the URI should contain the `conversionRequestId` that was used for the creation of the quote.
     * @summary Retrieve FX quote information
     * @param {FxQuotesApiFxQuotesByIDGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FxQuotesApi
     */
    public fxQuotesByIDGet(requestParameters: FxQuotesApiFxQuotesByIDGetRequest, options?: RawAxiosRequestConfig) {
        return FxQuotesApiFp(this.configuration).fxQuotesByIDGet(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.accept, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The callback `PUT /fxQuotes/{ID}` is used to inform the requester about the  outcome of a request for quotation for a currency conversion.  The `{ID}` in the URI should contain the `conversionRequestId` that was used for the  creation of the FX quote, or the `{ID}` that was used in the `GET /fxQuotes/{ID}` request.
     * @summary Return FX quote information
     * @param {FxQuotesApiFxQuotesByIdPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FxQuotesApi
     */
    public fxQuotesByIdPut(requestParameters: FxQuotesApiFxQuotesByIdPutRequest, options?: RawAxiosRequestConfig) {
        return FxQuotesApiFp(this.configuration).fxQuotesByIdPut(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.fxQuotesIDPutResponse, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, requestParameters.contentLength, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The HTTP request `POST /fxQuotes` is used to ask an FXP to provide a quotation for a currency conversion.
     * @summary Calculate FX quote
     * @param {FxQuotesApiFxQuotesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FxQuotesApi
     */
    public fxQuotesPost(requestParameters: FxQuotesApiFxQuotesPostRequest, options?: RawAxiosRequestConfig) {
        return FxQuotesApiFp(this.configuration).fxQuotesPost(requestParameters.accept, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.fxQuotesPostRequest, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(this.axios, this.basePath));
    }
}

