/* tslint:disable */
/* eslint-disable */
/**
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorInformationObject } from '../model';
// @ts-ignore
import type { ErrorInformationResponse } from '../model';
// @ts-ignore
import type { FxTransfersIDPatchResponse } from '../model';
// @ts-ignore
import type { FxTransfersIDPutResponse } from '../model';
// @ts-ignore
import type { FxTransfersPostRequest } from '../model';
/**
 * FxTransfersApi - axios parameter creator
 * @export
 */
export const FxTransfersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * If the switch or FXP is unable to find or create a FX transfer, or another processing error occurs, the error callback `PUT /fxTransfers/{ID}/error` is used. The `{ID}` in the URI should contain the `commitRequestId` that was used for the creation of the FX transfer, or the `{ID}` that was used in the `GET /fxTransfers/{ID}`.
         * @summary Return FX transfer information error
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {ErrorInformationObject} errorInformationObject Details of the error returned.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxTransfersByIDAndErrorPut: async (iD: string, contentType: string, date: string, fSPIOPSource: string, errorInformationObject: ErrorInformationObject, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('fxTransfersByIDAndErrorPut', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('fxTransfersByIDAndErrorPut', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('fxTransfersByIDAndErrorPut', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('fxTransfersByIDAndErrorPut', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'errorInformationObject' is not null or undefined
            assertParamExists('fxTransfersByIDAndErrorPut', 'errorInformationObject', errorInformationObject)
            const localVarPath = `/fxTransfers/{ID}/error`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(errorInformationObject, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The HTTP request `GET /fxTransfers/{ID}` s used to request information regarding a request for confirmation of a currency conversion which the sender has previously issued. The `{ID}` in the URI should contain the `commitRequestId` that was used for the creation of the FX transfer.
         * @summary Retrieve FX transfer information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxTransfersByIDGet: async (iD: string, contentType: string, date: string, fSPIOPSource: string, accept: string, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('fxTransfersByIDGet', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('fxTransfersByIDGet', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('fxTransfersByIDGet', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('fxTransfersByIDGet', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'accept' is not null or undefined
            assertParamExists('fxTransfersByIDGet', 'accept', accept)
            const localVarPath = `/fxTransfers/{ID}`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The HTTP request PATCH /fxTransfers/<ID> is used to inform the requester about the final determination by the switch of the transfer a request for execution of a currency conversion. The <ID> in the URI should contain the commitRequestId that was used for the creation of the FX transfer. Please note that this request does not generate a callback.
         * @summary Return FX transfer information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {FxTransfersIDPatchResponse} fxTransfersIDPatchResponse Transfer notification upon completion.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxTransfersByIDPatch: async (iD: string, contentType: string, date: string, fSPIOPSource: string, fxTransfersIDPatchResponse: FxTransfersIDPatchResponse, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, contentLength?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('fxTransfersByIDPatch', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('fxTransfersByIDPatch', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('fxTransfersByIDPatch', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('fxTransfersByIDPatch', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'fxTransfersIDPatchResponse' is not null or undefined
            assertParamExists('fxTransfersByIDPatch', 'fxTransfersIDPatchResponse', fxTransfersIDPatchResponse)
            const localVarPath = `/fxTransfers/{ID}`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fxTransfersIDPatchResponse, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The callback `PUT /fxTransfers/{ID}` is used to inform the requester about the outcome of a request for execution of a currency conversion. The `{ID}` in the URI should contain the `commitRequestId` that was used for the creation of the FX transfer, or the `{ID}` that was used in the `GET /fxTransfers/{ID}` request.
         * @summary Return FX transfer information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {FxTransfersIDPutResponse} fxTransfersIDPutResponse Transfer information returned.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxTransfersByIDPut: async (iD: string, contentType: string, date: string, fSPIOPSource: string, fxTransfersIDPutResponse: FxTransfersIDPutResponse, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, contentLength?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('fxTransfersByIDPut', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('fxTransfersByIDPut', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('fxTransfersByIDPut', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('fxTransfersByIDPut', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'fxTransfersIDPutResponse' is not null or undefined
            assertParamExists('fxTransfersByIDPut', 'fxTransfersIDPutResponse', fxTransfersIDPutResponse)
            const localVarPath = `/fxTransfers/{ID}`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fxTransfersIDPutResponse, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The HTTP request `POST /fxTransfers` is used to ask an FXP to confirm the execution of an agreed currency conversion.
         * @summary Perform FX transfer
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {FxTransfersPostRequest} fxTransfersPostRequest Details of the FX transfer to be created.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxTransfersPost: async (accept: string, contentType: string, date: string, fSPIOPSource: string, fxTransfersPostRequest: FxTransfersPostRequest, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accept' is not null or undefined
            assertParamExists('fxTransfersPost', 'accept', accept)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('fxTransfersPost', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('fxTransfersPost', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('fxTransfersPost', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'fxTransfersPostRequest' is not null or undefined
            assertParamExists('fxTransfersPost', 'fxTransfersPostRequest', fxTransfersPostRequest)
            const localVarPath = `/fxTransfers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fxTransfersPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FxTransfersApi - functional programming interface
 * @export
 */
export const FxTransfersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FxTransfersApiAxiosParamCreator(configuration)
    return {
        /**
         * If the switch or FXP is unable to find or create a FX transfer, or another processing error occurs, the error callback `PUT /fxTransfers/{ID}/error` is used. The `{ID}` in the URI should contain the `commitRequestId` that was used for the creation of the FX transfer, or the `{ID}` that was used in the `GET /fxTransfers/{ID}`.
         * @summary Return FX transfer information error
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {ErrorInformationObject} errorInformationObject Details of the error returned.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fxTransfersByIDAndErrorPut(iD: string, contentType: string, date: string, fSPIOPSource: string, errorInformationObject: ErrorInformationObject, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fxTransfersByIDAndErrorPut(iD, contentType, date, fSPIOPSource, errorInformationObject, contentLength, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FxTransfersApi.fxTransfersByIDAndErrorPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The HTTP request `GET /fxTransfers/{ID}` s used to request information regarding a request for confirmation of a currency conversion which the sender has previously issued. The `{ID}` in the URI should contain the `commitRequestId` that was used for the creation of the FX transfer.
         * @summary Retrieve FX transfer information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fxTransfersByIDGet(iD: string, contentType: string, date: string, fSPIOPSource: string, accept: string, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fxTransfersByIDGet(iD, contentType, date, fSPIOPSource, accept, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FxTransfersApi.fxTransfersByIDGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The HTTP request PATCH /fxTransfers/<ID> is used to inform the requester about the final determination by the switch of the transfer a request for execution of a currency conversion. The <ID> in the URI should contain the commitRequestId that was used for the creation of the FX transfer. Please note that this request does not generate a callback.
         * @summary Return FX transfer information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {FxTransfersIDPatchResponse} fxTransfersIDPatchResponse Transfer notification upon completion.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fxTransfersByIDPatch(iD: string, contentType: string, date: string, fSPIOPSource: string, fxTransfersIDPatchResponse: FxTransfersIDPatchResponse, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, contentLength?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fxTransfersByIDPatch(iD, contentType, date, fSPIOPSource, fxTransfersIDPatchResponse, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, contentLength, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FxTransfersApi.fxTransfersByIDPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The callback `PUT /fxTransfers/{ID}` is used to inform the requester about the outcome of a request for execution of a currency conversion. The `{ID}` in the URI should contain the `commitRequestId` that was used for the creation of the FX transfer, or the `{ID}` that was used in the `GET /fxTransfers/{ID}` request.
         * @summary Return FX transfer information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {FxTransfersIDPutResponse} fxTransfersIDPutResponse Transfer information returned.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fxTransfersByIDPut(iD: string, contentType: string, date: string, fSPIOPSource: string, fxTransfersIDPutResponse: FxTransfersIDPutResponse, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, contentLength?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fxTransfersByIDPut(iD, contentType, date, fSPIOPSource, fxTransfersIDPutResponse, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, contentLength, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FxTransfersApi.fxTransfersByIDPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The HTTP request `POST /fxTransfers` is used to ask an FXP to confirm the execution of an agreed currency conversion.
         * @summary Perform FX transfer
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {FxTransfersPostRequest} fxTransfersPostRequest Details of the FX transfer to be created.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fxTransfersPost(accept: string, contentType: string, date: string, fSPIOPSource: string, fxTransfersPostRequest: FxTransfersPostRequest, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fxTransfersPost(accept, contentType, date, fSPIOPSource, fxTransfersPostRequest, contentLength, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FxTransfersApi.fxTransfersPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FxTransfersApi - factory interface
 * @export
 */
export const FxTransfersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FxTransfersApiFp(configuration)
    return {
        /**
         * If the switch or FXP is unable to find or create a FX transfer, or another processing error occurs, the error callback `PUT /fxTransfers/{ID}/error` is used. The `{ID}` in the URI should contain the `commitRequestId` that was used for the creation of the FX transfer, or the `{ID}` that was used in the `GET /fxTransfers/{ID}`.
         * @summary Return FX transfer information error
         * @param {FxTransfersApiFxTransfersByIDAndErrorPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxTransfersByIDAndErrorPut(requestParameters: FxTransfersApiFxTransfersByIDAndErrorPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.fxTransfersByIDAndErrorPut(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.errorInformationObject, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(axios, basePath));
        },
        /**
         * The HTTP request `GET /fxTransfers/{ID}` s used to request information regarding a request for confirmation of a currency conversion which the sender has previously issued. The `{ID}` in the URI should contain the `commitRequestId` that was used for the creation of the FX transfer.
         * @summary Retrieve FX transfer information
         * @param {FxTransfersApiFxTransfersByIDGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxTransfersByIDGet(requestParameters: FxTransfersApiFxTransfersByIDGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.fxTransfersByIDGet(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.accept, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(axios, basePath));
        },
        /**
         * The HTTP request PATCH /fxTransfers/<ID> is used to inform the requester about the final determination by the switch of the transfer a request for execution of a currency conversion. The <ID> in the URI should contain the commitRequestId that was used for the creation of the FX transfer. Please note that this request does not generate a callback.
         * @summary Return FX transfer information
         * @param {FxTransfersApiFxTransfersByIDPatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxTransfersByIDPatch(requestParameters: FxTransfersApiFxTransfersByIDPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.fxTransfersByIDPatch(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.fxTransfersIDPatchResponse, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, requestParameters.contentLength, options).then((request) => request(axios, basePath));
        },
        /**
         * The callback `PUT /fxTransfers/{ID}` is used to inform the requester about the outcome of a request for execution of a currency conversion. The `{ID}` in the URI should contain the `commitRequestId` that was used for the creation of the FX transfer, or the `{ID}` that was used in the `GET /fxTransfers/{ID}` request.
         * @summary Return FX transfer information
         * @param {FxTransfersApiFxTransfersByIDPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxTransfersByIDPut(requestParameters: FxTransfersApiFxTransfersByIDPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.fxTransfersByIDPut(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.fxTransfersIDPutResponse, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, requestParameters.contentLength, options).then((request) => request(axios, basePath));
        },
        /**
         * The HTTP request `POST /fxTransfers` is used to ask an FXP to confirm the execution of an agreed currency conversion.
         * @summary Perform FX transfer
         * @param {FxTransfersApiFxTransfersPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fxTransfersPost(requestParameters: FxTransfersApiFxTransfersPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.fxTransfersPost(requestParameters.accept, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.fxTransfersPostRequest, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for fxTransfersByIDAndErrorPut operation in FxTransfersApi.
 * @export
 * @interface FxTransfersApiFxTransfersByIDAndErrorPutRequest
 */
export interface FxTransfersApiFxTransfersByIDAndErrorPutRequest {
    /**
     * The identifier value.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDAndErrorPut
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDAndErrorPut
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDAndErrorPut
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDAndErrorPut
     */
    readonly fSPIOPSource: string

    /**
     * Details of the error returned.
     * @type {ErrorInformationObject}
     * @memberof FxTransfersApiFxTransfersByIDAndErrorPut
     */
    readonly errorInformationObject: ErrorInformationObject

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof FxTransfersApiFxTransfersByIDAndErrorPut
     */
    readonly contentLength?: number

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDAndErrorPut
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDAndErrorPut
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDAndErrorPut
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDAndErrorPut
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDAndErrorPut
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDAndErrorPut
     */
    readonly fSPIOPHTTPMethod?: string
}

/**
 * Request parameters for fxTransfersByIDGet operation in FxTransfersApi.
 * @export
 * @interface FxTransfersApiFxTransfersByIDGetRequest
 */
export interface FxTransfersApiFxTransfersByIDGetRequest {
    /**
     * The identifier value.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDGet
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDGet
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDGet
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDGet
     */
    readonly fSPIOPSource: string

    /**
     * The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDGet
     */
    readonly accept: string

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDGet
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDGet
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDGet
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDGet
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDGet
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDGet
     */
    readonly fSPIOPHTTPMethod?: string
}

/**
 * Request parameters for fxTransfersByIDPatch operation in FxTransfersApi.
 * @export
 * @interface FxTransfersApiFxTransfersByIDPatchRequest
 */
export interface FxTransfersApiFxTransfersByIDPatchRequest {
    /**
     * The identifier value.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPatch
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPatch
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPatch
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPatch
     */
    readonly fSPIOPSource: string

    /**
     * Transfer notification upon completion.
     * @type {FxTransfersIDPatchResponse}
     * @memberof FxTransfersApiFxTransfersByIDPatch
     */
    readonly fxTransfersIDPatchResponse: FxTransfersIDPatchResponse

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPatch
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPatch
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPatch
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPatch
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPatch
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPatch
     */
    readonly fSPIOPHTTPMethod?: string

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof FxTransfersApiFxTransfersByIDPatch
     */
    readonly contentLength?: number
}

/**
 * Request parameters for fxTransfersByIDPut operation in FxTransfersApi.
 * @export
 * @interface FxTransfersApiFxTransfersByIDPutRequest
 */
export interface FxTransfersApiFxTransfersByIDPutRequest {
    /**
     * The identifier value.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPut
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPut
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPut
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPut
     */
    readonly fSPIOPSource: string

    /**
     * Transfer information returned.
     * @type {FxTransfersIDPutResponse}
     * @memberof FxTransfersApiFxTransfersByIDPut
     */
    readonly fxTransfersIDPutResponse: FxTransfersIDPutResponse

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPut
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPut
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPut
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPut
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPut
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersByIDPut
     */
    readonly fSPIOPHTTPMethod?: string

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof FxTransfersApiFxTransfersByIDPut
     */
    readonly contentLength?: number
}

/**
 * Request parameters for fxTransfersPost operation in FxTransfersApi.
 * @export
 * @interface FxTransfersApiFxTransfersPostRequest
 */
export interface FxTransfersApiFxTransfersPostRequest {
    /**
     * The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersPost
     */
    readonly accept: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersPost
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersPost
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersPost
     */
    readonly fSPIOPSource: string

    /**
     * Details of the FX transfer to be created.
     * @type {FxTransfersPostRequest}
     * @memberof FxTransfersApiFxTransfersPost
     */
    readonly fxTransfersPostRequest: FxTransfersPostRequest

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof FxTransfersApiFxTransfersPost
     */
    readonly contentLength?: number

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersPost
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersPost
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersPost
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof FxTransfersApiFxTransfersPost
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersPost
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof FxTransfersApiFxTransfersPost
     */
    readonly fSPIOPHTTPMethod?: string
}

/**
 * FxTransfersApi - object-oriented interface
 * @export
 * @class FxTransfersApi
 * @extends {BaseAPI}
 */
export class FxTransfersApi extends BaseAPI {
    /**
     * If the switch or FXP is unable to find or create a FX transfer, or another processing error occurs, the error callback `PUT /fxTransfers/{ID}/error` is used. The `{ID}` in the URI should contain the `commitRequestId` that was used for the creation of the FX transfer, or the `{ID}` that was used in the `GET /fxTransfers/{ID}`.
     * @summary Return FX transfer information error
     * @param {FxTransfersApiFxTransfersByIDAndErrorPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FxTransfersApi
     */
    public fxTransfersByIDAndErrorPut(requestParameters: FxTransfersApiFxTransfersByIDAndErrorPutRequest, options?: RawAxiosRequestConfig) {
        return FxTransfersApiFp(this.configuration).fxTransfersByIDAndErrorPut(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.errorInformationObject, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The HTTP request `GET /fxTransfers/{ID}` s used to request information regarding a request for confirmation of a currency conversion which the sender has previously issued. The `{ID}` in the URI should contain the `commitRequestId` that was used for the creation of the FX transfer.
     * @summary Retrieve FX transfer information
     * @param {FxTransfersApiFxTransfersByIDGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FxTransfersApi
     */
    public fxTransfersByIDGet(requestParameters: FxTransfersApiFxTransfersByIDGetRequest, options?: RawAxiosRequestConfig) {
        return FxTransfersApiFp(this.configuration).fxTransfersByIDGet(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.accept, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The HTTP request PATCH /fxTransfers/<ID> is used to inform the requester about the final determination by the switch of the transfer a request for execution of a currency conversion. The <ID> in the URI should contain the commitRequestId that was used for the creation of the FX transfer. Please note that this request does not generate a callback.
     * @summary Return FX transfer information
     * @param {FxTransfersApiFxTransfersByIDPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FxTransfersApi
     */
    public fxTransfersByIDPatch(requestParameters: FxTransfersApiFxTransfersByIDPatchRequest, options?: RawAxiosRequestConfig) {
        return FxTransfersApiFp(this.configuration).fxTransfersByIDPatch(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.fxTransfersIDPatchResponse, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, requestParameters.contentLength, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The callback `PUT /fxTransfers/{ID}` is used to inform the requester about the outcome of a request for execution of a currency conversion. The `{ID}` in the URI should contain the `commitRequestId` that was used for the creation of the FX transfer, or the `{ID}` that was used in the `GET /fxTransfers/{ID}` request.
     * @summary Return FX transfer information
     * @param {FxTransfersApiFxTransfersByIDPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FxTransfersApi
     */
    public fxTransfersByIDPut(requestParameters: FxTransfersApiFxTransfersByIDPutRequest, options?: RawAxiosRequestConfig) {
        return FxTransfersApiFp(this.configuration).fxTransfersByIDPut(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.fxTransfersIDPutResponse, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, requestParameters.contentLength, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The HTTP request `POST /fxTransfers` is used to ask an FXP to confirm the execution of an agreed currency conversion.
     * @summary Perform FX transfer
     * @param {FxTransfersApiFxTransfersPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FxTransfersApi
     */
    public fxTransfersPost(requestParameters: FxTransfersApiFxTransfersPostRequest, options?: RawAxiosRequestConfig) {
        return FxTransfersApiFp(this.configuration).fxTransfersPost(requestParameters.accept, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.fxTransfersPostRequest, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(this.axios, this.basePath));
    }
}

