/* tslint:disable */
/* eslint-disable */
/**
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorInformationObject } from '../model';
// @ts-ignore
import type { ErrorInformationResponse } from '../model';
// @ts-ignore
import type { QuotesIDPutResponse } from '../model';
// @ts-ignore
import type { QuotesPostRequest } from '../model';
/**
 * QuotesApi - axios parameter creator
 * @export
 */
export const QuotesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * The HTTP request `POST /quotes` is used to request the creation of a quote for the provided financial transaction in the server.
         * @summary Calculate quote
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {QuotesPostRequest} quotesPostRequest Details of the quote to be created.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotes: async (accept: string, contentType: string, date: string, fSPIOPSource: string, quotesPostRequest: QuotesPostRequest, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accept' is not null or undefined
            assertParamExists('quotes', 'accept', accept)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('quotes', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('quotes', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('quotes', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'quotesPostRequest' is not null or undefined
            assertParamExists('quotes', 'quotesPostRequest', quotesPostRequest)
            const localVarPath = `/quotes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(quotesPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The HTTP request `GET /quotes/{ID}` is used to get information regarding a quote created or requested earlier. The `{ID}` in the URI should contain the `quoteId` that was used for the creation of the quote.
         * @summary Retrieve quote information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotesByID: async (iD: string, contentType: string, date: string, fSPIOPSource: string, accept: string, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('quotesByID', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('quotesByID', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('quotesByID', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('quotesByID', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'accept' is not null or undefined
            assertParamExists('quotesByID', 'accept', accept)
            const localVarPath = `/quotes/{ID}`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The callback `PUT /quotes/{ID}` is used to inform the client of a requested or created quote. The `{ID}` in the URI should contain the `quoteId` that was used for the creation of the quote, or the `{ID}` that was used in the `GET /quotes/{ID}` request.
         * @summary Return quote information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {QuotesIDPutResponse} quotesIDPutResponse Quote information returned.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotesByID1: async (iD: string, contentType: string, date: string, fSPIOPSource: string, quotesIDPutResponse: QuotesIDPutResponse, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, contentLength?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('quotesByID1', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('quotesByID1', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('quotesByID1', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('quotesByID1', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'quotesIDPutResponse' is not null or undefined
            assertParamExists('quotesByID1', 'quotesIDPutResponse', quotesIDPutResponse)
            const localVarPath = `/quotes/{ID}`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(quotesIDPutResponse, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * If the server is unable to find or create a quote, or some other processing error occurs, the error callback `PUT /quotes/{ID}/error` is used. The `{ID}` in the URI should contain the `quoteId` that was used for the creation of the quote, or the `{ID}` that was used in the `GET /quotes/{ID}` request.
         * @summary Return quote information error
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {ErrorInformationObject} errorInformationObject Details of the error returned.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotesByIDAndError: async (iD: string, contentType: string, date: string, fSPIOPSource: string, errorInformationObject: ErrorInformationObject, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('quotesByIDAndError', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('quotesByIDAndError', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('quotesByIDAndError', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('quotesByIDAndError', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'errorInformationObject' is not null or undefined
            assertParamExists('quotesByIDAndError', 'errorInformationObject', errorInformationObject)
            const localVarPath = `/quotes/{ID}/error`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(errorInformationObject, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuotesApi - functional programming interface
 * @export
 */
export const QuotesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QuotesApiAxiosParamCreator(configuration)
    return {
        /**
         * The HTTP request `POST /quotes` is used to request the creation of a quote for the provided financial transaction in the server.
         * @summary Calculate quote
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {QuotesPostRequest} quotesPostRequest Details of the quote to be created.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quotes(accept: string, contentType: string, date: string, fSPIOPSource: string, quotesPostRequest: QuotesPostRequest, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quotes(accept, contentType, date, fSPIOPSource, quotesPostRequest, contentLength, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuotesApi.quotes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The HTTP request `GET /quotes/{ID}` is used to get information regarding a quote created or requested earlier. The `{ID}` in the URI should contain the `quoteId` that was used for the creation of the quote.
         * @summary Retrieve quote information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quotesByID(iD: string, contentType: string, date: string, fSPIOPSource: string, accept: string, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quotesByID(iD, contentType, date, fSPIOPSource, accept, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuotesApi.quotesByID']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The callback `PUT /quotes/{ID}` is used to inform the client of a requested or created quote. The `{ID}` in the URI should contain the `quoteId` that was used for the creation of the quote, or the `{ID}` that was used in the `GET /quotes/{ID}` request.
         * @summary Return quote information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {QuotesIDPutResponse} quotesIDPutResponse Quote information returned.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quotesByID1(iD: string, contentType: string, date: string, fSPIOPSource: string, quotesIDPutResponse: QuotesIDPutResponse, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, contentLength?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quotesByID1(iD, contentType, date, fSPIOPSource, quotesIDPutResponse, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, contentLength, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuotesApi.quotesByID1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * If the server is unable to find or create a quote, or some other processing error occurs, the error callback `PUT /quotes/{ID}/error` is used. The `{ID}` in the URI should contain the `quoteId` that was used for the creation of the quote, or the `{ID}` that was used in the `GET /quotes/{ID}` request.
         * @summary Return quote information error
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {ErrorInformationObject} errorInformationObject Details of the error returned.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quotesByIDAndError(iD: string, contentType: string, date: string, fSPIOPSource: string, errorInformationObject: ErrorInformationObject, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quotesByIDAndError(iD, contentType, date, fSPIOPSource, errorInformationObject, contentLength, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuotesApi.quotesByIDAndError']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QuotesApi - factory interface
 * @export
 */
export const QuotesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QuotesApiFp(configuration)
    return {
        /**
         * The HTTP request `POST /quotes` is used to request the creation of a quote for the provided financial transaction in the server.
         * @summary Calculate quote
         * @param {QuotesApiQuotesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotes(requestParameters: QuotesApiQuotesRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.quotes(requestParameters.accept, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.quotesPostRequest, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(axios, basePath));
        },
        /**
         * The HTTP request `GET /quotes/{ID}` is used to get information regarding a quote created or requested earlier. The `{ID}` in the URI should contain the `quoteId` that was used for the creation of the quote.
         * @summary Retrieve quote information
         * @param {QuotesApiQuotesByIDRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotesByID(requestParameters: QuotesApiQuotesByIDRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.quotesByID(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.accept, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(axios, basePath));
        },
        /**
         * The callback `PUT /quotes/{ID}` is used to inform the client of a requested or created quote. The `{ID}` in the URI should contain the `quoteId` that was used for the creation of the quote, or the `{ID}` that was used in the `GET /quotes/{ID}` request.
         * @summary Return quote information
         * @param {QuotesApiQuotesByID1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotesByID1(requestParameters: QuotesApiQuotesByID1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.quotesByID1(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.quotesIDPutResponse, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, requestParameters.contentLength, options).then((request) => request(axios, basePath));
        },
        /**
         * If the server is unable to find or create a quote, or some other processing error occurs, the error callback `PUT /quotes/{ID}/error` is used. The `{ID}` in the URI should contain the `quoteId` that was used for the creation of the quote, or the `{ID}` that was used in the `GET /quotes/{ID}` request.
         * @summary Return quote information error
         * @param {QuotesApiQuotesByIDAndErrorRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotesByIDAndError(requestParameters: QuotesApiQuotesByIDAndErrorRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.quotesByIDAndError(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.errorInformationObject, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for quotes operation in QuotesApi.
 * @export
 * @interface QuotesApiQuotesRequest
 */
export interface QuotesApiQuotesRequest {
    /**
     * The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
     * @type {string}
     * @memberof QuotesApiQuotes
     */
    readonly accept: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof QuotesApiQuotes
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof QuotesApiQuotes
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof QuotesApiQuotes
     */
    readonly fSPIOPSource: string

    /**
     * Details of the quote to be created.
     * @type {QuotesPostRequest}
     * @memberof QuotesApiQuotes
     */
    readonly quotesPostRequest: QuotesPostRequest

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof QuotesApiQuotes
     */
    readonly contentLength?: number

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof QuotesApiQuotes
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof QuotesApiQuotes
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof QuotesApiQuotes
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof QuotesApiQuotes
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof QuotesApiQuotes
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof QuotesApiQuotes
     */
    readonly fSPIOPHTTPMethod?: string
}

/**
 * Request parameters for quotesByID operation in QuotesApi.
 * @export
 * @interface QuotesApiQuotesByIDRequest
 */
export interface QuotesApiQuotesByIDRequest {
    /**
     * The identifier value.
     * @type {string}
     * @memberof QuotesApiQuotesByID
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof QuotesApiQuotesByID
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof QuotesApiQuotesByID
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof QuotesApiQuotesByID
     */
    readonly fSPIOPSource: string

    /**
     * The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
     * @type {string}
     * @memberof QuotesApiQuotesByID
     */
    readonly accept: string

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof QuotesApiQuotesByID
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof QuotesApiQuotesByID
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof QuotesApiQuotesByID
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof QuotesApiQuotesByID
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof QuotesApiQuotesByID
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof QuotesApiQuotesByID
     */
    readonly fSPIOPHTTPMethod?: string
}

/**
 * Request parameters for quotesByID1 operation in QuotesApi.
 * @export
 * @interface QuotesApiQuotesByID1Request
 */
export interface QuotesApiQuotesByID1Request {
    /**
     * The identifier value.
     * @type {string}
     * @memberof QuotesApiQuotesByID1
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof QuotesApiQuotesByID1
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof QuotesApiQuotesByID1
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof QuotesApiQuotesByID1
     */
    readonly fSPIOPSource: string

    /**
     * Quote information returned.
     * @type {QuotesIDPutResponse}
     * @memberof QuotesApiQuotesByID1
     */
    readonly quotesIDPutResponse: QuotesIDPutResponse

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof QuotesApiQuotesByID1
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof QuotesApiQuotesByID1
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof QuotesApiQuotesByID1
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof QuotesApiQuotesByID1
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof QuotesApiQuotesByID1
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof QuotesApiQuotesByID1
     */
    readonly fSPIOPHTTPMethod?: string

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof QuotesApiQuotesByID1
     */
    readonly contentLength?: number
}

/**
 * Request parameters for quotesByIDAndError operation in QuotesApi.
 * @export
 * @interface QuotesApiQuotesByIDAndErrorRequest
 */
export interface QuotesApiQuotesByIDAndErrorRequest {
    /**
     * The identifier value.
     * @type {string}
     * @memberof QuotesApiQuotesByIDAndError
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof QuotesApiQuotesByIDAndError
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof QuotesApiQuotesByIDAndError
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof QuotesApiQuotesByIDAndError
     */
    readonly fSPIOPSource: string

    /**
     * Details of the error returned.
     * @type {ErrorInformationObject}
     * @memberof QuotesApiQuotesByIDAndError
     */
    readonly errorInformationObject: ErrorInformationObject

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof QuotesApiQuotesByIDAndError
     */
    readonly contentLength?: number

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof QuotesApiQuotesByIDAndError
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof QuotesApiQuotesByIDAndError
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof QuotesApiQuotesByIDAndError
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof QuotesApiQuotesByIDAndError
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof QuotesApiQuotesByIDAndError
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof QuotesApiQuotesByIDAndError
     */
    readonly fSPIOPHTTPMethod?: string
}

/**
 * QuotesApi - object-oriented interface
 * @export
 * @class QuotesApi
 * @extends {BaseAPI}
 */
export class QuotesApi extends BaseAPI {
    /**
     * The HTTP request `POST /quotes` is used to request the creation of a quote for the provided financial transaction in the server.
     * @summary Calculate quote
     * @param {QuotesApiQuotesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuotesApi
     */
    public quotes(requestParameters: QuotesApiQuotesRequest, options?: RawAxiosRequestConfig) {
        return QuotesApiFp(this.configuration).quotes(requestParameters.accept, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.quotesPostRequest, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The HTTP request `GET /quotes/{ID}` is used to get information regarding a quote created or requested earlier. The `{ID}` in the URI should contain the `quoteId` that was used for the creation of the quote.
     * @summary Retrieve quote information
     * @param {QuotesApiQuotesByIDRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuotesApi
     */
    public quotesByID(requestParameters: QuotesApiQuotesByIDRequest, options?: RawAxiosRequestConfig) {
        return QuotesApiFp(this.configuration).quotesByID(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.accept, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The callback `PUT /quotes/{ID}` is used to inform the client of a requested or created quote. The `{ID}` in the URI should contain the `quoteId` that was used for the creation of the quote, or the `{ID}` that was used in the `GET /quotes/{ID}` request.
     * @summary Return quote information
     * @param {QuotesApiQuotesByID1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuotesApi
     */
    public quotesByID1(requestParameters: QuotesApiQuotesByID1Request, options?: RawAxiosRequestConfig) {
        return QuotesApiFp(this.configuration).quotesByID1(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.quotesIDPutResponse, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, requestParameters.contentLength, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * If the server is unable to find or create a quote, or some other processing error occurs, the error callback `PUT /quotes/{ID}/error` is used. The `{ID}` in the URI should contain the `quoteId` that was used for the creation of the quote, or the `{ID}` that was used in the `GET /quotes/{ID}` request.
     * @summary Return quote information error
     * @param {QuotesApiQuotesByIDAndErrorRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuotesApi
     */
    public quotesByIDAndError(requestParameters: QuotesApiQuotesByIDAndErrorRequest, options?: RawAxiosRequestConfig) {
        return QuotesApiFp(this.configuration).quotesByIDAndError(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.errorInformationObject, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(this.axios, this.basePath));
    }
}

