/* tslint:disable */
/* eslint-disable */
/**
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorInformationObject } from '../model';
// @ts-ignore
import type { ErrorInformationResponse } from '../model';
// @ts-ignore
import type { TransactionsIDPutResponse } from '../model';
/**
 * TransactionsApi - axios parameter creator
 * @export
 */
export const TransactionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * The HTTP request `GET /transactions/{ID}` is used to get transaction information regarding a financial transaction created earlier. The `{ID}` in the URI should contain the `transactionId` that was used for the creation of the quote, as the transaction is created as part of another process (the transfer process).
         * @summary Retrieve transaction information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsByID: async (iD: string, contentType: string, date: string, fSPIOPSource: string, accept: string, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('transactionsByID', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('transactionsByID', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('transactionsByID', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('transactionsByID', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'accept' is not null or undefined
            assertParamExists('transactionsByID', 'accept', accept)
            const localVarPath = `/transactions/{ID}`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The callback `PUT /transactions/{ID}` is used to inform the client of a requested transaction. The `{ID}` in the URI should contain the `{ID}` that was used in the `GET /transactions/{ID}` request.
         * @summary Return transaction information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {TransactionsIDPutResponse} transactionsIDPutResponse Transaction information returned.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsByID1: async (iD: string, contentType: string, date: string, fSPIOPSource: string, transactionsIDPutResponse: TransactionsIDPutResponse, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, contentLength?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('transactionsByID1', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('transactionsByID1', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('transactionsByID1', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('transactionsByID1', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'transactionsIDPutResponse' is not null or undefined
            assertParamExists('transactionsByID1', 'transactionsIDPutResponse', transactionsIDPutResponse)
            const localVarPath = `/transactions/{ID}`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(transactionsIDPutResponse, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * If the server is unable to find or create a transaction, or another processing error occurs, the error callback `PUT /transactions/{ID}/error` is used. The `{ID}` in the URI should contain the `{ID}` that was used in the `GET /transactions/{ID}` request.
         * @summary Return transaction information error
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {ErrorInformationObject} errorInformationObject Details of the error returned.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsErrorByID: async (iD: string, contentType: string, date: string, fSPIOPSource: string, errorInformationObject: ErrorInformationObject, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iD' is not null or undefined
            assertParamExists('transactionsErrorByID', 'iD', iD)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('transactionsErrorByID', 'contentType', contentType)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('transactionsErrorByID', 'date', date)
            // verify required parameter 'fSPIOPSource' is not null or undefined
            assertParamExists('transactionsErrorByID', 'fSPIOPSource', fSPIOPSource)
            // verify required parameter 'errorInformationObject' is not null or undefined
            assertParamExists('transactionsErrorByID', 'errorInformationObject', errorInformationObject)
            const localVarPath = `/transactions/{ID}/error`
                .replace(`{${"ID"}}`, encodeURIComponent(String(iD)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (contentLength != null) {
                localVarHeaderParameter['Content-Length'] = typeof contentLength === 'string'
                    ? contentLength
                    : JSON.stringify(contentLength);
            }
            if (contentType != null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }
            if (date != null) {
                localVarHeaderParameter['Date'] = String(date);
            }
            if (xForwardedFor != null) {
                localVarHeaderParameter['X-Forwarded-For'] = String(xForwardedFor);
            }
            if (fSPIOPSource != null) {
                localVarHeaderParameter['FSPIOP-Source'] = String(fSPIOPSource);
            }
            if (fSPIOPDestination != null) {
                localVarHeaderParameter['FSPIOP-Destination'] = String(fSPIOPDestination);
            }
            if (fSPIOPEncryption != null) {
                localVarHeaderParameter['FSPIOP-Encryption'] = String(fSPIOPEncryption);
            }
            if (fSPIOPSignature != null) {
                localVarHeaderParameter['FSPIOP-Signature'] = String(fSPIOPSignature);
            }
            if (fSPIOPURI != null) {
                localVarHeaderParameter['FSPIOP-URI'] = String(fSPIOPURI);
            }
            if (fSPIOPHTTPMethod != null) {
                localVarHeaderParameter['FSPIOP-HTTP-Method'] = String(fSPIOPHTTPMethod);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(errorInformationObject, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransactionsApi - functional programming interface
 * @export
 */
export const TransactionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransactionsApiAxiosParamCreator(configuration)
    return {
        /**
         * The HTTP request `GET /transactions/{ID}` is used to get transaction information regarding a financial transaction created earlier. The `{ID}` in the URI should contain the `transactionId` that was used for the creation of the quote, as the transaction is created as part of another process (the transfer process).
         * @summary Retrieve transaction information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {string} accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transactionsByID(iD: string, contentType: string, date: string, fSPIOPSource: string, accept: string, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transactionsByID(iD, contentType, date, fSPIOPSource, accept, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.transactionsByID']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The callback `PUT /transactions/{ID}` is used to inform the client of a requested transaction. The `{ID}` in the URI should contain the `{ID}` that was used in the `GET /transactions/{ID}` request.
         * @summary Return transaction information
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {TransactionsIDPutResponse} transactionsIDPutResponse Transaction information returned.
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transactionsByID1(iD: string, contentType: string, date: string, fSPIOPSource: string, transactionsIDPutResponse: TransactionsIDPutResponse, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, contentLength?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transactionsByID1(iD, contentType, date, fSPIOPSource, transactionsIDPutResponse, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, contentLength, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.transactionsByID1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * If the server is unable to find or create a transaction, or another processing error occurs, the error callback `PUT /transactions/{ID}/error` is used. The `{ID}` in the URI should contain the `{ID}` that was used in the `GET /transactions/{ID}` request.
         * @summary Return transaction information error
         * @param {string} iD The identifier value.
         * @param {string} contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
         * @param {string} date The &#x60;Date&#x60; header field indicates the date when the request was sent.
         * @param {string} fSPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
         * @param {ErrorInformationObject} errorInformationObject Details of the error returned.
         * @param {number} [contentLength] The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         * @param {string} [xForwardedFor] The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
         * @param {string} [fSPIOPDestination] The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
         * @param {string} [fSPIOPEncryption] The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
         * @param {string} [fSPIOPSignature] The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
         * @param {string} [fSPIOPURI] The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {string} [fSPIOPHTTPMethod] The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transactionsErrorByID(iD: string, contentType: string, date: string, fSPIOPSource: string, errorInformationObject: ErrorInformationObject, contentLength?: number, xForwardedFor?: string, fSPIOPDestination?: string, fSPIOPEncryption?: string, fSPIOPSignature?: string, fSPIOPURI?: string, fSPIOPHTTPMethod?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transactionsErrorByID(iD, contentType, date, fSPIOPSource, errorInformationObject, contentLength, xForwardedFor, fSPIOPDestination, fSPIOPEncryption, fSPIOPSignature, fSPIOPURI, fSPIOPHTTPMethod, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.transactionsErrorByID']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TransactionsApi - factory interface
 * @export
 */
export const TransactionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransactionsApiFp(configuration)
    return {
        /**
         * The HTTP request `GET /transactions/{ID}` is used to get transaction information regarding a financial transaction created earlier. The `{ID}` in the URI should contain the `transactionId` that was used for the creation of the quote, as the transaction is created as part of another process (the transfer process).
         * @summary Retrieve transaction information
         * @param {TransactionsApiTransactionsByIDRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsByID(requestParameters: TransactionsApiTransactionsByIDRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.transactionsByID(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.accept, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(axios, basePath));
        },
        /**
         * The callback `PUT /transactions/{ID}` is used to inform the client of a requested transaction. The `{ID}` in the URI should contain the `{ID}` that was used in the `GET /transactions/{ID}` request.
         * @summary Return transaction information
         * @param {TransactionsApiTransactionsByID1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsByID1(requestParameters: TransactionsApiTransactionsByID1Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.transactionsByID1(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.transactionsIDPutResponse, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, requestParameters.contentLength, options).then((request) => request(axios, basePath));
        },
        /**
         * If the server is unable to find or create a transaction, or another processing error occurs, the error callback `PUT /transactions/{ID}/error` is used. The `{ID}` in the URI should contain the `{ID}` that was used in the `GET /transactions/{ID}` request.
         * @summary Return transaction information error
         * @param {TransactionsApiTransactionsErrorByIDRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsErrorByID(requestParameters: TransactionsApiTransactionsErrorByIDRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.transactionsErrorByID(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.errorInformationObject, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for transactionsByID operation in TransactionsApi.
 * @export
 * @interface TransactionsApiTransactionsByIDRequest
 */
export interface TransactionsApiTransactionsByIDRequest {
    /**
     * The identifier value.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof TransactionsApiTransactionsByID
     */
    readonly fSPIOPSource: string

    /**
     * The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID
     */
    readonly accept: string

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof TransactionsApiTransactionsByID
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof TransactionsApiTransactionsByID
     */
    readonly fSPIOPHTTPMethod?: string
}

/**
 * Request parameters for transactionsByID1 operation in TransactionsApi.
 * @export
 * @interface TransactionsApiTransactionsByID1Request
 */
export interface TransactionsApiTransactionsByID1Request {
    /**
     * The identifier value.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID1
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID1
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID1
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof TransactionsApiTransactionsByID1
     */
    readonly fSPIOPSource: string

    /**
     * Transaction information returned.
     * @type {TransactionsIDPutResponse}
     * @memberof TransactionsApiTransactionsByID1
     */
    readonly transactionsIDPutResponse: TransactionsIDPutResponse

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID1
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID1
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID1
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof TransactionsApiTransactionsByID1
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof TransactionsApiTransactionsByID1
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof TransactionsApiTransactionsByID1
     */
    readonly fSPIOPHTTPMethod?: string

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof TransactionsApiTransactionsByID1
     */
    readonly contentLength?: number
}

/**
 * Request parameters for transactionsErrorByID operation in TransactionsApi.
 * @export
 * @interface TransactionsApiTransactionsErrorByIDRequest
 */
export interface TransactionsApiTransactionsErrorByIDRequest {
    /**
     * The identifier value.
     * @type {string}
     * @memberof TransactionsApiTransactionsErrorByID
     */
    readonly iD: string

    /**
     * The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body.
     * @type {string}
     * @memberof TransactionsApiTransactionsErrorByID
     */
    readonly contentType: string

    /**
     * The &#x60;Date&#x60; header field indicates the date when the request was sent.
     * @type {string}
     * @memberof TransactionsApiTransactionsErrorByID
     */
    readonly date: string

    /**
     * The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;).
     * @type {string}
     * @memberof TransactionsApiTransactionsErrorByID
     */
    readonly fSPIOPSource: string

    /**
     * Details of the error returned.
     * @type {ErrorInformationObject}
     * @memberof TransactionsApiTransactionsErrorByID
     */
    readonly errorInformationObject: ErrorInformationObject

    /**
     * The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     * @type {number}
     * @memberof TransactionsApiTransactionsErrorByID
     */
    readonly contentLength?: number

    /**
     * The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;.
     * @type {string}
     * @memberof TransactionsApiTransactionsErrorByID
     */
    readonly xForwardedFor?: string

    /**
     * The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty.
     * @type {string}
     * @memberof TransactionsApiTransactionsErrorByID
     */
    readonly fSPIOPDestination?: string

    /**
     * The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
     * @type {string}
     * @memberof TransactionsApiTransactionsErrorByID
     */
    readonly fSPIOPEncryption?: string

    /**
     * The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
     * @type {string}
     * @memberof TransactionsApiTransactionsErrorByID
     */
    readonly fSPIOPSignature?: string

    /**
     * The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof TransactionsApiTransactionsErrorByID
     */
    readonly fSPIOPURI?: string

    /**
     * The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set).
     * @type {string}
     * @memberof TransactionsApiTransactionsErrorByID
     */
    readonly fSPIOPHTTPMethod?: string
}

/**
 * TransactionsApi - object-oriented interface
 * @export
 * @class TransactionsApi
 * @extends {BaseAPI}
 */
export class TransactionsApi extends BaseAPI {
    /**
     * The HTTP request `GET /transactions/{ID}` is used to get transaction information regarding a financial transaction created earlier. The `{ID}` in the URI should contain the `transactionId` that was used for the creation of the quote, as the transaction is created as part of another process (the transfer process).
     * @summary Retrieve transaction information
     * @param {TransactionsApiTransactionsByIDRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public transactionsByID(requestParameters: TransactionsApiTransactionsByIDRequest, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).transactionsByID(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.accept, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The callback `PUT /transactions/{ID}` is used to inform the client of a requested transaction. The `{ID}` in the URI should contain the `{ID}` that was used in the `GET /transactions/{ID}` request.
     * @summary Return transaction information
     * @param {TransactionsApiTransactionsByID1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public transactionsByID1(requestParameters: TransactionsApiTransactionsByID1Request, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).transactionsByID1(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.transactionsIDPutResponse, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, requestParameters.contentLength, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * If the server is unable to find or create a transaction, or another processing error occurs, the error callback `PUT /transactions/{ID}/error` is used. The `{ID}` in the URI should contain the `{ID}` that was used in the `GET /transactions/{ID}` request.
     * @summary Return transaction information error
     * @param {TransactionsApiTransactionsErrorByIDRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public transactionsErrorByID(requestParameters: TransactionsApiTransactionsErrorByIDRequest, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).transactionsErrorByID(requestParameters.iD, requestParameters.contentType, requestParameters.date, requestParameters.fSPIOPSource, requestParameters.errorInformationObject, requestParameters.contentLength, requestParameters.xForwardedFor, requestParameters.fSPIOPDestination, requestParameters.fSPIOPEncryption, requestParameters.fSPIOPSignature, requestParameters.fSPIOPURI, requestParameters.fSPIOPHTTPMethod, options).then((request) => request(this.axios, this.basePath));
    }
}

