#!/bin/sh
# Points the CloudHSM client at this deployment's cluster, then starts the service.
#
# The library finds its cluster through a configuration file it owns, not through the environment,
# so something has to write that file before the application loads it. Written at startup rather
# than baked into the image because the address differs per environment, and generated by the
# vendor's own tool rather than hand-written because the file's format belongs to the SDK and has
# changed between releases -- a hand-written one would break silently on an upgrade.
#
# Does nothing unless CLOUDHSM_IP is set, so the same image serves every profile: a deployment
# signing in software, or against SoftHSM, starts unchanged.
set -e

if [ -n "${CLOUDHSM_IP:-}" ]; then

    if [ ! -f /opt/cloudhsm/etc/customerCA.crt ]; then
        # Refused rather than started. Without the certificate the client cannot confirm it reached
        # your cluster, and the failure would otherwise surface much later as a login error that
        # says nothing about a missing file.
        echo "CLOUDHSM_IP is set but /opt/cloudhsm/etc/customerCA.crt is missing." >&2
        echo "Mount the cluster certificate there -- it is public, so a ConfigMap is enough." >&2
        exit 1
    fi

    /opt/cloudhsm/bin/configure-pkcs11 -a "$CLOUDHSM_IP"
    echo "CloudHSM client configured for $CLOUDHSM_IP."
fi

# exec, so the service is PID 1 and receives the signals Kubernetes sends it. Without this a
# SIGTERM reaches the shell instead, and the pod is killed rather than shut down -- which for a
# signing service means dropping whatever it was in the middle of.
exec "$@"
