// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ThitsaWorks
/**
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PartyResult} from './party-result';
import {Currency} from './currency';
import { ApiProperty } from '@nestjs/swagger';


/**
 * The object sent in the PUT /participants/{ID} callback.
 */
export class ParticipantsIDPutResponse { 
    /**
     * List of PartyResult elements that were either created or failed to be created.
     */
    @ApiProperty({type: () => PartyResult, isArray: true})
    partyList!: Array<PartyResult>;
    currency?: Currency;
}



