// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ThitsaWorks
/**
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PartyIdType} from './party-id-type';
import {ExtensionList} from './extension-list';
import { ApiProperty } from '@nestjs/swagger';


/**
 * Data model for the complex type PartyIdInfo. An ExtensionList element has been added to this reqeust in version v1.1
 */
export class PartyIdInfo { 
    @ApiProperty({enum: PartyIdType, enumName: 'PartyIdType'})
    partyIdType!: PartyIdType;
    /**
     * Identifier of the Party.
     */
    @ApiProperty({type: String})
    partyIdentifier!: string;
    /**
     * Either a sub-identifier of a PartyIdentifier, or a sub-type of the PartyIdType, normally a PersonalIdentifierType.
     */
    @ApiProperty({type: String, required: false})
    partySubIdOrType?: string;
    /**
     * FSP identifier.
     */
    @ApiProperty({type: String, required: false})
    fspId?: string;
    extensionList?: ExtensionList;
}



