// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 ThitsaWorks
/**
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Below are the allowed values for the enumeration. - PASSPORT - A passport number is used as reference to a Party. - NATIONAL_REGISTRATION - A national registration number is used as reference to a Party. - DRIVING_LICENSE - A driving license is used as reference to a Party. - ALIEN_REGISTRATION - An alien registration number is used as reference to a Party. - NATIONAL_ID_CARD - A national ID card number is used as reference to a Party. - EMPLOYER_ID - A tax identification number is used as reference to a Party. - TAX_ID_NUMBER - A tax identification number is used as reference to a Party. - SENIOR_CITIZENS_CARD - A senior citizens card number is used as reference to a Party. - MARRIAGE_CERTIFICATE - A marriage certificate number is used as reference to a Party. - HEALTH_CARD - A health card number is used as reference to a Party. - VOTERS_ID - A voter’s identification number is used as reference to a Party. - UNITED_NATIONS - An UN (United Nations) number is used as reference to a Party. - OTHER_ID - Any other type of identification type number is used as reference to a Party.
 */
export enum PersonalIdentifierType {
    Passport = 'PASSPORT',
    NationalRegistration = 'NATIONAL_REGISTRATION',
    DrivingLicense = 'DRIVING_LICENSE',
    AlienRegistration = 'ALIEN_REGISTRATION',
    NationalIdCard = 'NATIONAL_ID_CARD',
    EmployerId = 'EMPLOYER_ID',
    TaxIdNumber = 'TAX_ID_NUMBER',
    SeniorCitizensCard = 'SENIOR_CITIZENS_CARD',
    MarriageCertificate = 'MARRIAGE_CERTIFICATE',
    HealthCard = 'HEALTH_CARD',
    VotersId = 'VOTERS_ID',
    UnitedNations = 'UNITED_NATIONS',
    OtherId = 'OTHER_ID'
}

