import { Currency } from '../dto/currency';

export type FspiopCurrency = Currency;

export interface FspiopCurrencyProfile {
    currency: Currency;
    name: string;
    scale: number;
}

export class FspiopCurrencies {

    private static readonly CURRENCIES: Readonly<Record<Currency, FspiopCurrencyProfile>> = {
        [Currency.Aed]: { currency: Currency.Aed, name: 'UAE dirham', scale: 2 },
        [Currency.Afn]: { currency: Currency.Afn, name: 'Afghanistan afghani', scale: 2 },
        [Currency.All]: { currency: Currency.All, name: 'Albanian lek', scale: 2 },
        [Currency.Amd]: { currency: Currency.Amd, name: 'Armenian dram', scale: 2 },
        [Currency.Ang]: { currency: Currency.Ang, name: 'Netherlands Antillian guilder', scale: 2 },
        [Currency.Aoa]: { currency: Currency.Aoa, name: 'Angolan kwanza', scale: 2 },
        [Currency.Ars]: { currency: Currency.Ars, name: 'Argentine peso', scale: 2 },
        [Currency.Aud]: { currency: Currency.Aud, name: 'Australian dollar', scale: 2 },
        [Currency.Awg]: { currency: Currency.Awg, name: 'Aruban guilder', scale: 2 },
        [Currency.Azn]: { currency: Currency.Azn, name: 'Azerbaijanian new manat', scale: 2 },
        [Currency.Bam]: { currency: Currency.Bam, name: 'Bosnia-Herzegovina convertible mark', scale: 2 },
        [Currency.Bbd]: { currency: Currency.Bbd, name: 'Barbados dollar', scale: 2 },
        [Currency.Bdt]: { currency: Currency.Bdt, name: 'Bangladeshi taka', scale: 2 },
        [Currency.Bgn]: { currency: Currency.Bgn, name: 'Bulgarian lev', scale: 2 },
        [Currency.Bhd]: { currency: Currency.Bhd, name: 'Bahraini dinar', scale: 3 },
        [Currency.Bif]: { currency: Currency.Bif, name: 'Burundi franc', scale: 0 },
        [Currency.Bmd]: { currency: Currency.Bmd, name: 'Bermudian dollar', scale: 2 },
        [Currency.Bnd]: { currency: Currency.Bnd, name: 'Brunei dollar', scale: 2 },
        [Currency.Bob]: { currency: Currency.Bob, name: 'Bolivian boliviano', scale: 2 },
        [Currency.Brl]: { currency: Currency.Brl, name: 'Brazilian real', scale: 2 },
        [Currency.Bsd]: { currency: Currency.Bsd, name: 'Bahamian dollar', scale: 2 },
        [Currency.Btn]: { currency: Currency.Btn, name: 'Bhutan ngultrum', scale: 2 },
        [Currency.Bwp]: { currency: Currency.Bwp, name: 'Botswana pula', scale: 2 },
        [Currency.Byn]: { currency: Currency.Byn, name: 'Belarusian ruble', scale: 4 },
        [Currency.Bzd]: { currency: Currency.Bzd, name: 'Belize dollar', scale: 2 },
        [Currency.Cad]: { currency: Currency.Cad, name: 'Canadian dollar', scale: 2 },
        [Currency.Cdf]: { currency: Currency.Cdf, name: 'Congolese franc', scale: 2 },
        [Currency.Chf]: { currency: Currency.Chf, name: 'Swiss franc', scale: 2 },
        [Currency.Clp]: { currency: Currency.Clp, name: 'Chilean peso', scale: 0 },
        [Currency.Cny]: { currency: Currency.Cny, name: 'Chinese yuan renminbi', scale: 2 },
        [Currency.Cop]: { currency: Currency.Cop, name: 'Colombian peso', scale: 2 },
        [Currency.Crc]: { currency: Currency.Crc, name: 'Costa Rican colon', scale: 2 },
        [Currency.Cuc]: { currency: Currency.Cuc, name: 'Cuban convertible peso', scale: 2 },
        [Currency.Cup]: { currency: Currency.Cup, name: 'Cuban peso', scale: 2 },
        [Currency.Cve]: { currency: Currency.Cve, name: 'Cape Verde escudo', scale: 2 },
        [Currency.Czk]: { currency: Currency.Czk, name: 'Czech koruna', scale: 2 },
        [Currency.Djf]: { currency: Currency.Djf, name: 'Djibouti franc', scale: 0 },
        [Currency.Dkk]: { currency: Currency.Dkk, name: 'Danish krone', scale: 2 },
        [Currency.Dop]: { currency: Currency.Dop, name: 'Dominican peso', scale: 2 },
        [Currency.Dzd]: { currency: Currency.Dzd, name: 'Algerian dinar', scale: 2 },
        [Currency.Egp]: { currency: Currency.Egp, name: 'Egyptian pound', scale: 2 },
        [Currency.Ern]: { currency: Currency.Ern, name: 'Eritrean nakfa', scale: 2 },
        [Currency.Etb]: { currency: Currency.Etb, name: 'Ethiopian birr', scale: 2 },
        [Currency.Eur]: { currency: Currency.Eur, name: 'EU euro', scale: 2 },
        [Currency.Fjd]: { currency: Currency.Fjd, name: 'Fiji dollar', scale: 2 },
        [Currency.Fkp]: { currency: Currency.Fkp, name: 'Falkland Islands pound', scale: 2 },
        [Currency.Gbp]: { currency: Currency.Gbp, name: 'British pound', scale: 2 },
        [Currency.Gel]: { currency: Currency.Gel, name: 'Georgian lari', scale: 2 },
        [Currency.Ggp]: { currency: Currency.Ggp, name: 'Guernsey pound', scale: 4 },
        [Currency.Ghs]: { currency: Currency.Ghs, name: 'Ghanaian new cedi', scale: 2 },
        [Currency.Gip]: { currency: Currency.Gip, name: 'Gibraltar pound', scale: 2 },
        [Currency.Gmd]: { currency: Currency.Gmd, name: 'Gambian dalasi', scale: 2 },
        [Currency.Gnf]: { currency: Currency.Gnf, name: 'Guinean franc', scale: 0 },
        [Currency.Gtq]: { currency: Currency.Gtq, name: 'Guatemalan quetzal', scale: 2 },
        [Currency.Gyd]: { currency: Currency.Gyd, name: 'Guyana dollar', scale: 2 },
        [Currency.Hkd]: { currency: Currency.Hkd, name: 'Hong Kong SAR dollar', scale: 2 },
        [Currency.Hnl]: { currency: Currency.Hnl, name: 'Honduran lempira', scale: 2 },
        [Currency.Hrk]: { currency: Currency.Hrk, name: 'Croatian kuna', scale: 2 },
        [Currency.Htg]: { currency: Currency.Htg, name: 'Haitian gourde', scale: 2 },
        [Currency.Huf]: { currency: Currency.Huf, name: 'Hungarian forint', scale: 2 },
        [Currency.Idr]: { currency: Currency.Idr, name: 'Indonesian rupiah', scale: 2 },
        [Currency.Ils]: { currency: Currency.Ils, name: 'Israeli new shekel', scale: 2 },
        [Currency.Imp]: { currency: Currency.Imp, name: 'Isle of Man pound', scale: 4 },
        [Currency.Inr]: { currency: Currency.Inr, name: 'Indian rupee', scale: 2 },
        [Currency.Iqd]: { currency: Currency.Iqd, name: 'Iraqi dinar', scale: 3 },
        [Currency.Irr]: { currency: Currency.Irr, name: 'Iranian rial', scale: 2 },
        [Currency.Isk]: { currency: Currency.Isk, name: 'Icelandic krona', scale: 0 },
        [Currency.Jep]: { currency: Currency.Jep, name: 'Jersey pound', scale: 4 },
        [Currency.Jmd]: { currency: Currency.Jmd, name: 'Jamaican dollar', scale: 2 },
        [Currency.Jod]: { currency: Currency.Jod, name: 'Jordanian dinar', scale: 3 },
        [Currency.Jpy]: { currency: Currency.Jpy, name: 'Japanese yen', scale: 0 },
        [Currency.Kes]: { currency: Currency.Kes, name: 'Kenyan shilling', scale: 2 },
        [Currency.Kgs]: { currency: Currency.Kgs, name: 'Kyrgyz som', scale: 2 },
        [Currency.Khr]: { currency: Currency.Khr, name: 'Cambodian riel', scale: 2 },
        [Currency.Kmf]: { currency: Currency.Kmf, name: 'Comoros franc', scale: 0 },
        [Currency.Kpw]: { currency: Currency.Kpw, name: 'North Korean won', scale: 2 },
        [Currency.Krw]: { currency: Currency.Krw, name: 'South Korean won', scale: 0 },
        [Currency.Kwd]: { currency: Currency.Kwd, name: 'Kuwaiti dinar', scale: 3 },
        [Currency.Kyd]: { currency: Currency.Kyd, name: 'Cayman Islands dollar', scale: 2 },
        [Currency.Kzt]: { currency: Currency.Kzt, name: 'Kazakh tenge', scale: 2 },
        [Currency.Lak]: { currency: Currency.Lak, name: 'Lao kip', scale: 2 },
        [Currency.Lbp]: { currency: Currency.Lbp, name: 'Lebanese pound', scale: 2 },
        [Currency.Lkr]: { currency: Currency.Lkr, name: 'Sri Lanka rupee', scale: 2 },
        [Currency.Lrd]: { currency: Currency.Lrd, name: 'Liberian dollar', scale: 2 },
        [Currency.Lsl]: { currency: Currency.Lsl, name: 'Lesotho loti', scale: 2 },
        [Currency.Lyd]: { currency: Currency.Lyd, name: 'Libyan dinar', scale: 3 },
        [Currency.Mad]: { currency: Currency.Mad, name: 'Moroccan dirham', scale: 2 },
        [Currency.Mdl]: { currency: Currency.Mdl, name: 'Moldovan leu', scale: 2 },
        [Currency.Mga]: { currency: Currency.Mga, name: 'Malagasy ariary', scale: 2 },
        [Currency.Mkd]: { currency: Currency.Mkd, name: 'Macedonian denar', scale: 2 },
        [Currency.Mmk]: { currency: Currency.Mmk, name: 'Myanmar kyat', scale: 2 },
        [Currency.Mnt]: { currency: Currency.Mnt, name: 'Mongolian tugrik', scale: 2 },
        [Currency.Mop]: { currency: Currency.Mop, name: 'Macao SAR pataca', scale: 2 },
        [Currency.Mro]: { currency: Currency.Mro, name: 'Mauritanian ouguiya', scale: 2 },
        [Currency.Mur]: { currency: Currency.Mur, name: 'Mauritius rupee', scale: 2 },
        [Currency.Mvr]: { currency: Currency.Mvr, name: 'Maldivian rufiyaa', scale: 2 },
        [Currency.Mwk]: { currency: Currency.Mwk, name: 'Malawi kwacha', scale: 2 },
        [Currency.Mxn]: { currency: Currency.Mxn, name: 'Mexican peso', scale: 2 },
        [Currency.Myr]: { currency: Currency.Myr, name: 'Malaysian ringgit', scale: 2 },
        [Currency.Mzn]: { currency: Currency.Mzn, name: 'Mozambique new metical', scale: 2 },
        [Currency.Nad]: { currency: Currency.Nad, name: 'Namibian dollar', scale: 2 },
        [Currency.Ngn]: { currency: Currency.Ngn, name: 'Nigerian naira', scale: 2 },
        [Currency.Nio]: { currency: Currency.Nio, name: 'Nicaraguan cordoba oro', scale: 2 },
        [Currency.Nok]: { currency: Currency.Nok, name: 'Norwegian krone', scale: 2 },
        [Currency.Npr]: { currency: Currency.Npr, name: 'Nepalese rupee', scale: 2 },
        [Currency.Nzd]: { currency: Currency.Nzd, name: 'New Zealand dollar', scale: 2 },
        [Currency.Omr]: { currency: Currency.Omr, name: 'Omani rial', scale: 3 },
        [Currency.Pab]: { currency: Currency.Pab, name: 'Panamanian balboa', scale: 2 },
        [Currency.Pen]: { currency: Currency.Pen, name: 'Peruvian nuevo sol', scale: 2 },
        [Currency.Pgk]: { currency: Currency.Pgk, name: 'Papua New Guinea kina', scale: 2 },
        [Currency.Php]: { currency: Currency.Php, name: 'Philippine peso', scale: 2 },
        [Currency.Pkr]: { currency: Currency.Pkr, name: 'Pakistani rupee', scale: 2 },
        [Currency.Pln]: { currency: Currency.Pln, name: 'Polish zloty', scale: 2 },
        [Currency.Pyg]: { currency: Currency.Pyg, name: 'Paraguayan guarani', scale: 0 },
        [Currency.Qar]: { currency: Currency.Qar, name: 'Qatari rial', scale: 2 },
        [Currency.Ron]: { currency: Currency.Ron, name: 'Romanian new leu', scale: 2 },
        [Currency.Rsd]: { currency: Currency.Rsd, name: 'Serbian dinar', scale: 2 },
        [Currency.Rub]: { currency: Currency.Rub, name: 'Russian ruble', scale: 2 },
        [Currency.Rwf]: { currency: Currency.Rwf, name: 'Rwandan franc', scale: 0 },
        [Currency.Sar]: { currency: Currency.Sar, name: 'Saudi riyal', scale: 2 },
        [Currency.Sbd]: { currency: Currency.Sbd, name: 'Solomon Islands dollar', scale: 2 },
        [Currency.Scr]: { currency: Currency.Scr, name: 'Seychelles rupee', scale: 2 },
        [Currency.Sdg]: { currency: Currency.Sdg, name: 'Sudanese pound', scale: 2 },
        [Currency.Sek]: { currency: Currency.Sek, name: 'Swedish krona', scale: 2 },
        [Currency.Sgd]: { currency: Currency.Sgd, name: 'Singapore dollar', scale: 2 },
        [Currency.Shp]: { currency: Currency.Shp, name: 'Saint Helena pound', scale: 2 },
        [Currency.Sll]: { currency: Currency.Sll, name: 'Sierra Leone leone', scale: 2 },
        [Currency.Sos]: { currency: Currency.Sos, name: 'Somali shilling', scale: 2 },
        [Currency.Spl]: { currency: Currency.Spl, name: 'Seborgan luigino', scale: 4 },
        [Currency.Srd]: { currency: Currency.Srd, name: 'Suriname dollar', scale: 2 },
        [Currency.Std]: { currency: Currency.Std, name: 'Sao Tome and Principe dobra', scale: 2 },
        [Currency.Svc]: { currency: Currency.Svc, name: 'El Salvador colon', scale: 2 },
        [Currency.Syp]: { currency: Currency.Syp, name: 'Syrian pound', scale: 2 },
        [Currency.Szl]: { currency: Currency.Szl, name: 'Swaziland lilangeni', scale: 2 },
        [Currency.Thb]: { currency: Currency.Thb, name: 'Thai baht', scale: 2 },
        [Currency.Tjs]: { currency: Currency.Tjs, name: 'Tajik somoni', scale: 2 },
        [Currency.Tmt]: { currency: Currency.Tmt, name: 'Turkmen new manat', scale: 2 },
        [Currency.Tnd]: { currency: Currency.Tnd, name: 'Tunisian dinar', scale: 3 },
        [Currency.Top]: { currency: Currency.Top, name: 'Tongan pa\'anga', scale: 2 },
        [Currency.Try]: { currency: Currency.Try, name: 'Turkish lira', scale: 2 },
        [Currency.Ttd]: { currency: Currency.Ttd, name: 'Trinidad and Tobago dollar', scale: 2 },
        [Currency.Tvd]: { currency: Currency.Tvd, name: 'Tuvaluan dollar', scale: 4 },
        [Currency.Twd]: { currency: Currency.Twd, name: 'Taiwan New dollar', scale: 2 },
        [Currency.Tzs]: { currency: Currency.Tzs, name: 'Tanzanian shilling', scale: 2 },
        [Currency.Uah]: { currency: Currency.Uah, name: 'Ukrainian hryvnia', scale: 2 },
        [Currency.Ugx]: { currency: Currency.Ugx, name: 'Uganda new shilling', scale: 0 },
        [Currency.Usd]: { currency: Currency.Usd, name: 'US dollar', scale: 2 },
        [Currency.Uyu]: { currency: Currency.Uyu, name: 'Uruguayan peso uruguayo', scale: 2 },
        [Currency.Uzs]: { currency: Currency.Uzs, name: 'Uzbekistani sum', scale: 2 },
        [Currency.Vef]: { currency: Currency.Vef, name: 'Venezuelan bolivar fuerte', scale: 2 },
        [Currency.Vnd]: { currency: Currency.Vnd, name: 'Vietnamese dong', scale: 0 },
        [Currency.Vuv]: { currency: Currency.Vuv, name: 'Vanuatu vatu', scale: 0 },
        [Currency.Wst]: { currency: Currency.Wst, name: 'Samoan tala', scale: 2 },
        [Currency.Xaf]: { currency: Currency.Xaf, name: 'CFA franc BEAC', scale: 0 },
        [Currency.Xcd]: { currency: Currency.Xcd, name: 'East Caribbean dollar', scale: 2 },
        [Currency.Xdr]: { currency: Currency.Xdr, name: 'IMF special drawing right', scale: 4 },
        [Currency.Xof]: { currency: Currency.Xof, name: 'CFA franc BCEAO', scale: 0 },
        [Currency.Xpf]: { currency: Currency.Xpf, name: 'CFP franc', scale: 0 },
        [Currency.Xts]: { currency: Currency.Xts, name: 'Reserved for testing purposes', scale: 4 },
        [Currency.Xxx]: { currency: Currency.Xxx, name: 'Assigned for transactions where no currency is involved', scale: 4 },
        [Currency.Yer]: { currency: Currency.Yer, name: 'Yemeni rial', scale: 2 },
        [Currency.Zar]: { currency: Currency.Zar, name: 'South African rand', scale: 2 },
        [Currency.Zmw]: { currency: Currency.Zmw, name: 'Zambian kwacha', scale: 2 },
        [Currency.Zwd]: { currency: Currency.Zwd, name: 'Zimbabwe dollar (initial)', scale: 4 },
    };

    static get(currency: Currency): FspiopCurrencyProfile | undefined {
        return FspiopCurrencies.CURRENCIES[currency];
    }
}
